"use client";

import { useState } from "react";
import type { WorkoutRecord,WorkoutSample } from "@/lib/performance-records";
import { formatPace } from "@/lib/performance-records";

type Series="paceSecondsPer500"|"spm"|"watts"|"heartRate"|"resistance";
const seriesMeta:Record<Series,{label:string;color:string;unit:string}>={paceSecondsPer500:{label:"Pace",color:"#ff6b35",unit:"/500 m"},spm:{label:"Stroke rate",color:"#16725e",unit:"spm"},watts:{label:"Watts",color:"#7756a8",unit:"W"},heartRate:{label:"Heart rate",color:"#c33c54",unit:"bpm"},resistance:{label:"Resistance",color:"#8a6a2f",unit:"level"}};
function has(samples:WorkoutSample[],key:Series){return samples.some((sample)=>sample[key]!=null)}

export function PerformanceChart({workout}:{workout:WorkoutRecord}){
 const available=(Object.keys(seriesMeta) as Series[]).filter((key)=>has(workout.samples,key));
 const [active,setActive]=useState<Series[]>(()=>available.filter((key)=>key==="paceSecondsPer500"||key==="spm"));
 const [hovered,setHovered]=useState<number|null>(null);
 if(!workout.samples.length)return <section className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7" aria-labelledby="performance-chart"><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Performance chart</p><h2 id="performance-chart" className="mt-2 text-2xl font-black">Telemetry not available</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#718078]">This record contains an imported summary only. Rowform does not generate synthetic stroke or time-series data.</p></section>;
 const width=900,height=280,pad=40; const maxX=Math.max(...workout.samples.map((s)=>s.offsetSeconds));
 function points(key:Series){const vals=workout.samples.map((s)=>s[key]).filter((v):v is number=>typeof v==="number");const min=Math.min(...vals),max=Math.max(...vals);return workout.samples.map((s)=>{const v=s[key];if(v==null)return null;const x=pad+(s.offsetSeconds/maxX)*(width-pad*2);const y=height-pad-((v-min)/(max-min||1))*(height-pad*2);return `${x},${y}`}).filter(Boolean).join(" ")}
 const point=hovered==null?null:workout.samples[hovered];
 return <section className="rounded-3xl border border-[#dfe5e1] bg-white p-4 sm:p-7" aria-labelledby="performance-chart"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Performance chart</p><h2 id="performance-chart" className="mt-2 text-2xl font-black">How the row unfolded</h2><p className="mt-2 text-xs text-[#718078]">Sample basis: {workout.sampleBasis}. Missing samples are not interpolated.</p></div><div className="flex flex-wrap gap-2" role="group" aria-label="Chart series">{available.map((key)=><button key={key} type="button" aria-pressed={active.includes(key)} onClick={()=>setActive((current)=>current.includes(key)?current.filter((item)=>item!==key):[...current,key])} className={`min-h-11 rounded-full border px-3 text-xs font-black focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#16725e] ${active.includes(key)?"border-transparent bg-[#0d2b24] text-white":"border-[#ccd6d1] bg-white"}`}><span className="mr-2 inline-block size-2 rounded-full" style={{background:seriesMeta[key].color}}/>{seriesMeta[key].label}</button>)}</div></div>
 <div className="relative mt-5 overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="min-w-[42rem]" role="img" aria-labelledby="chart-title chart-desc" onMouseLeave={()=>setHovered(null)}><title id="chart-title">Workout performance over elapsed time</title><desc id="chart-desc">Interactive chart of {active.map((key)=>seriesMeta[key].label).join(", ")} using {workout.sampleBasis} samples. The table below provides an accessible numeric summary.</desc>{[0,1,2,3,4].map((i)=><line key={i} x1={pad} x2={width-pad} y1={pad+i*50} y2={pad+i*50} stroke="#e4e9e6"/>)}<text x={pad} y={height-8} fontSize="11" fill="#718078">0:00</text><text x={width-pad} y={height-8} textAnchor="end" fontSize="11" fill="#718078">{Math.round(maxX/60)} min</text>{active.map((key)=><polyline key={key} points={points(key)} fill="none" stroke={seriesMeta[key].color} strokeWidth="4" strokeLinejoin="round"/>)}{workout.samples.map((sample,index)=><rect key={sample.offsetSeconds} x={pad+(sample.offsetSeconds/maxX)*(width-pad*2)-12} y={pad} width="24" height={height-pad*2} fill="transparent" tabIndex={0} onFocus={()=>setHovered(index)} onMouseEnter={()=>setHovered(index)} aria-label={`${Math.floor(sample.offsetSeconds/60)} minutes ${sample.offsetSeconds%60} seconds`}/>)}</svg>{point&&<div className="pointer-events-none absolute left-4 top-4 rounded-xl bg-[#0d2b24] p-3 text-xs text-white shadow-lg"><p className="font-black">{Math.floor(point.offsetSeconds/60)}:{String(point.offsetSeconds%60).padStart(2,"0")}</p>{active.map((key)=><p key={key} className="mt-1">{seriesMeta[key].label}: {key==="paceSecondsPer500"?formatPace(point[key]):point[key]} {seriesMeta[key].unit}</p>)}</div>}</div>
 <div className="sr-only"><table><caption>Chart sample summary</caption><thead><tr><th>Elapsed</th>{available.map((key)=><th key={key}>{seriesMeta[key].label}</th>)}</tr></thead><tbody>{workout.samples.map((sample)=><tr key={sample.offsetSeconds}><td>{sample.offsetSeconds} seconds</td>{available.map((key)=><td key={key}>{sample[key]??"Not recorded"}</td>)}</tr>)}</tbody></table></div></section>;
}
