import Link from "next/link";
import { ArrowLeft,CheckCircle2,Download,ExternalLink,Flag,LockKeyhole,Share2,ShieldCheck,Trash2 } from "lucide-react";
import type { ResultRecord,WorkoutRecord } from "@/lib/performance-records";
import { formatDistance,formatDuration,formatPace } from "@/lib/performance-records";
import { PerformanceChart } from "./performance-chart";

const card="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7";
const metric=(label:string,value:string,detail?:string)=><div className="min-w-0"><dt className="text-[10px] font-black uppercase tracking-[.12em] text-[#718078]">{label}</dt><dd className="mt-2 text-2xl font-black tabular-nums sm:text-3xl">{value}</dd>{detail&&<p className="mt-1 text-xs text-[#718078]">{detail}</p>}</div>;
const Field=({label,value}:{label:string;value?:string|number})=>value==null?null:<div><dt className="text-xs text-[#718078]">{label}</dt><dd className="mt-1 text-sm font-bold">{value}</dd></div>;

export function PerformanceDetail({workout,result}:{workout:WorkoutRecord;result?:ResultRecord}){
 const isTime=workout.kind==="fixed-time",isInterval=workout.kind==="interval"; const canEdit=workout.owner&&!result?.event;
 const metrics=isInterval?[metric("Work distance",formatDistance(workout.metrics.distanceMeters)),metric("Work duration",formatDuration(workout.metrics.durationSeconds)),metric("Intervals",String(workout.intervals.filter((i)=>i.segmentType==="work").length)),metric("Average watts",workout.metrics.averageWatts?`${workout.metrics.averageWatts} W`:"Not recorded"),metric("Stroke rate",workout.metrics.averageSpm?`${workout.metrics.averageSpm} spm`:"Not recorded")]:[metric(isTime?"Duration":"Distance",isTime?formatDuration(workout.metrics.durationSeconds):formatDistance(workout.metrics.distanceMeters)),metric(isTime?"Distance":"Total time",isTime?formatDistance(workout.metrics.distanceMeters):formatDuration(workout.metrics.durationSeconds)),metric("Average /500 m",formatPace(workout.metrics.paceSecondsPer500)),metric("Average watts",workout.metrics.averageWatts?`${workout.metrics.averageWatts} W`:"Not recorded"),metric("Stroke rate",workout.metrics.averageSpm?`${workout.metrics.averageSpm} spm`:"Not recorded"),...(workout.metrics.calories?[metric("Calories",`${workout.metrics.calories} kcal`)]:[])];
 return <div><Link href={result?result.ranking?`/leaderboard?${result.ranking.backQuery}`:result.event?`/events/${result.event.slug}#results`:"/workouts":"/workouts"} className="inline-flex min-h-11 items-center gap-2 text-sm font-black text-[#36534a] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#16725e]"><ArrowLeft size={17}/>Back to {result?.event?"Event results":result?.ranking?"filtered Rankings":"Workouts"}</Link>
 <header className="mt-3 overflow-hidden rounded-[2rem] bg-[#0d2b24] p-6 text-white surface-grid sm:p-9"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#ff6b35] px-3 py-1 text-[10px] font-black uppercase tracking-[.13em]">{result?.resultType??workout.resultType}</span><span className="inline-flex items-center gap-1 rounded-full border border-white/20 px-3 py-1 text-[10px] font-black"><ShieldCheck size={12}/>{workout.verification.label} · Tier {workout.verification.tier}</span>{result&&<span className="rounded-full border border-white/20 px-3 py-1 text-[10px] font-black">{result.rankingStatus}</span>}</div><h1 className="display-type mt-5 text-4xl font-black leading-none sm:text-6xl">{workout.title}</h1><p className="mt-4 text-base font-black">{workout.athlete.name} · {workout.athlete.countryCode}</p><p className="mt-1 text-sm text-white/65">{workout.athlete.affiliation} · <time dateTime={workout.startedAt}>{new Date(workout.startedAt).toLocaleString("en-GB",{dateStyle:"long",timeStyle:"short"})}</time></p>{result?.event&&<p className="mt-4 text-sm font-bold text-[#ffb094]">{result.event.eventName} · {result.event.race}</p>}</header>
 <dl className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-3xl border border-[#dfe5e1] bg-[#dfe5e1] sm:grid-cols-3 xl:grid-cols-6">{metrics.map((item,index)=><div key={index} className="bg-white p-4 sm:p-5">{item}</div>)}</dl>
 <div className="mt-5"><PerformanceChart workout={workout}/></div>
 {(workout.splits.length>0||workout.intervals.length>0)&&<section className={`${card} mt-5`} aria-labelledby="detail-table"><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">{isInterval?"Interval structure":"Official splits"}</p><h2 id="detail-table" className="mt-2 text-2xl font-black">{isInterval?"Work and recovery":"Split-by-split"}</h2><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b border-[#dfe5e1] text-[10px] uppercase tracking-[.1em] text-[#718078]"><th className="py-3">{isInterval?"Segment":"Split"}</th><th>Distance</th><th>Duration</th><th>Cumulative</th><th>Pace /500 m</th><th>Watts</th><th>SPM</th><th>Heart rate</th><th>Calories</th></tr></thead><tbody>{(isInterval?workout.intervals:workout.splits).map((row)=><tr key={row.id} className={`border-b border-[#edf0ee] last:border-0 ${"segmentType" in row&&row.segmentType==="recovery"?"bg-[#f5f7f4]":""}`}><td className="py-4 font-black">{"segmentType" in row?`${row.number}. ${row.segmentType}`:row.number}</td><td>{formatDistance(row.distanceMeters)}</td><td>{formatDuration(row.durationSeconds)}</td><td>{formatDuration(row.elapsedSeconds)}</td><td>{formatPace(row.paceSecondsPer500)}</td><td>{row.watts?`${row.watts} W`:"—"}</td><td>{row.spm??"—"}</td><td>{row.heartRate?`${row.heartRate} bpm`:"—"}</td><td>{row.calories??"—"}</td></tr>)}</tbody></table></div></section>}
 <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className={card}><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Verification and provenance</p><h2 className="mt-2 text-2xl font-black">Evidence chain</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Verification" value={`Tier ${workout.verification.tier} · ${workout.verification.label}`}/><Field label="Authority" value={workout.verification.authority}/><Field label="Source provider" value={workout.verification.sourceProvider}/><Field label="Import method" value={workout.verification.importMethod}/><Field label="Evidence type" value={workout.verification.evidenceType}/><Field label="Evidence timestamp" value={new Date(workout.verification.evidenceTimestamp).toLocaleString("en-GB")}/><Field label="Ranking eligibility" value={workout.verification.rankingEligible?"Eligible under the shown definition":"Not eligible"}/>{workout.verification.exclusionReason&&<Field label="Exclusion reason" value={workout.verification.exclusionReason}/>}</dl>{workout.verification.notes&&<p className="mt-5 rounded-xl bg-[#fff7f2] p-3 text-xs leading-5 text-[#6d4a3a]">{workout.verification.notes}</p>}</section>
 <section className={card}><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Machine and source</p><h2 className="mt-2 text-2xl font-black">Equipment record</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Brand" value={workout.machine.brand}/><Field label="Model" value={workout.machine.model}/><Field label="Machine class" value={workout.machine.machineClass}/><Field label="Monitor" value={workout.machine.monitor??"Not recorded"}/><Field label="Connection" value={workout.machine.connectionMethod}/><Field label="Drag factor" value={workout.machine.dragFactor}/><Field label="Resistance" value={workout.machine.resistanceLevel}/><Field label="Firmware" value={workout.machine.firmwareVersion}/></dl><p className="mt-5 inline-flex rounded-full bg-[#eaf6f1] px-3 py-2 text-xs font-black text-[#176a55]">{workout.machine.comparability}</p>{Object.keys(workout.providerMetrics).length>0&&<details className="mt-4"><summary className="cursor-pointer text-sm font-black text-[#16725e]">Provider-specific metrics</summary><dl className="mt-3 grid gap-3 rounded-xl bg-[#f5f7f4] p-4 sm:grid-cols-2">{Object.entries(workout.providerMetrics).map(([key,value])=><Field key={key} label={key.replaceAll(/([A-Z])/g," $1")} value={String(value)}/>)}</dl></details>}</section></div>
 {result?.ranking&&<section className={`${card} mt-5`}><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Ranking context</p><h2 className="mt-2 text-2xl font-black">#{result.ranking.position} of {result.ranking.eligibleCount}</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Definition" value={result.ranking.definition}/><Field label="Division" value={result.ranking.division}/><Field label="Age category" value={result.ranking.ageCategory}/><Field label="Weight category" value={result.ranking.weightCategory}/><Field label="Geography" value={result.ranking.geography}/><Field label="Format" value={result.ranking.format}/><Field label="Machine constraint" value={result.ranking.machineConstraints}/><Field label="Verification threshold" value={result.ranking.verificationThreshold}/></dl><Link href={`/leaderboard?${result.ranking.backQuery}`} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black">View exact ranking definition <ExternalLink size={15}/></Link></section>}
 {result?.event&&<section className={`${card} mt-5`}><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Event context</p><h2 className="mt-2 text-2xl font-black">{result.event.eventName}</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Organizer" value={result.event.organizer}/><Field label="Race" value={result.event.race}/><Field label="Stage" value={result.event.stage}/><Field label="Lane" value={result.event.lane}/><Field label="Entry number" value={result.event.bib}/><Field label="Position" value={result.event.position}/><Field label="Result state" value={result.event.status}/><Field label="Authority" value={result.event.authority}/></dl><Link href={`/events/${result.event.slug}#results`} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black">View race results <ExternalLink size={15}/></Link></section>}
 {workout.expedition&&<section className={`${card} mt-5`}><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Expedition contribution</p><h2 className="mt-2 text-2xl font-black">{workout.expedition.name}</h2><div className="mt-4 flex flex-wrap gap-4 text-sm"><strong>+{formatDistance(workout.expedition.contributedMeters)}</strong><span>{workout.expedition.checkpoint}</span><span>{workout.expedition.contributionDate}</span><span>{workout.expedition.active?"Active Expedition":"Completed Expedition"}</span></div><Link href={`/expeditions/${workout.expedition.slug}`} className="mt-5 inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black">View Expedition <Flag size={15}/></Link></section>}
 <section className={`${card} mt-5`}><p className="text-xs font-black uppercase tracking-[.15em] text-[#d94d1c]">Athlete record</p><h2 className="mt-2 text-2xl font-black">Notes, purpose and privacy</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Training purpose" value={workout.trainingPurpose??"Not recorded"}/><Field label="Perceived exertion" value={workout.perceivedExertion?`${workout.perceivedExertion} / 10`:"Not recorded"}/><Field label="Tags" value={workout.tags.join(", ")||"None"}/><Field label="Visibility" value={workout.visibility}/></dl>{workout.notes&&<p className="mt-5 rounded-xl bg-[#f5f7f4] p-4 text-sm leading-6"><LockKeyhole size={15} className="mr-2 inline text-[#16725e]"/>Private athlete note: {workout.notes}</p>}<p className="mt-3 text-xs text-[#718078]">Coach notes are reserved for a future authorized coaching relationship.</p></section>
 {result?.workoutId&&<div className="mt-5 rounded-2xl border border-[#dfe5e1] bg-[#f5f7f4] p-4 text-sm"><CheckCircle2 size={17} className="mr-2 inline text-[#16725e]"/>This competitive claim references the authoritative workout. <Link href={`/workouts/${result.workoutId}`} className="font-black text-[#16725e] underline underline-offset-4">Open workout record</Link>.</div>}
 <section className={`${card} mt-5`} aria-labelledby="actions"><h2 id="actions" className="text-xl font-black">Record actions</h2><div className="mt-4 flex flex-wrap gap-2"><button disabled={!canEdit} title={!canEdit?"Official Event results require an organizer correction workflow":undefined} className="min-h-11 rounded-full border border-[#ccd6d1] px-4 text-sm font-black disabled:cursor-not-allowed disabled:opacity-50">Edit workout</button><button className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black"><Download size={15}/>Download data</button><button className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black"><Share2 size={15}/>Share public-safe view</button><button className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black"><ExternalLink size={15}/>View original record</button>{!canEdit&&<button className="inline-flex min-h-11 items-center gap-2 rounded-full border border-[#ccd6d1] px-4 text-sm font-black">Report result</button>}{canEdit&&<button disabled title="Deletion requires persistence, dependency recalculation, and confirmation" className="inline-flex min-h-11 cursor-not-allowed items-center gap-2 rounded-full border border-[#e8c5ba] px-4 text-sm font-black text-[#a94420] opacity-60"><Trash2 size={15}/>Delete workout</button>}</div><p className="mt-3 text-xs leading-5 text-[#718078]">Prototype actions are intentionally non-destructive. Production edits preserve verification history; deletions recalculate Rankings and Expedition progress.</p></section></div>;
}
