export type PassportVisibility="Private"|"Connections only"|"Public athlete profile"|"Event organizers";
export type TrainingContext="Home"|"Commercial gym"|"Rowing club"|"School or university"|"National training centre"|"Other";
export interface CustomClubDraft{officialName:string;countryCode:string;country:string;city:string;website:string;federation:string}
export interface PassportAthlete{name:string;initials:string;country:string;countryCode:string;city:string;cityIsOther:boolean;cityRegion?:string;cityLatitude?:number;cityLongitude?:number;citySource?:"dataset"|"manual";trainingContext:TrainingContext;selectedClubId:string;customClub:CustomClubDraft;preferredMachineId:string;memberSince:string;currentSeason:string;passportId:string;verificationStatus:string;completion:number;preferredMachine:string;biography:string;visibility:PassportVisibility}
export interface PassportMetric{label:string;value:string;detail:string}
export interface PersonalBest{effort:string;result:string;date:string;machineClass:string;verification:string;improvement?:string}
export interface TimelineEntry{id:string;date:string;title:string;detail:string;kind:"identity"|"verified"|"performance"|"competition"|"expedition"|"ranking"|"community";eventResultId?:string;registrationId?:string}
export interface ActiveExpedition{name:string;subtitle:string;currentPosition:string;completedKm:number;totalKm:number;nextLandmark:string;distanceToNextKm:number}
export interface CompletedExpedition{name:string;completedOn:string;distance:string;certificate:string}
export interface CompetitionRecord{id:string;event:string;date:string;format:string;result:string;category:string;machineClass:string;verification:string;placing:string;eventId?:string;raceId?:string;eventResultId?:string;registrationId?:string;rankingRecordId?:string}
export interface Achievement{id:string;type:"Consistency"|"Improvement"|"Verified performance"|"Expedition"|"Event"|"Community"|"Lifetime";title:string;detail:string;earnedOn:string}
export interface PassportData{athlete:PassportAthlete;summary:PassportMetric[];personalBests:PersonalBest[];timeline:TimelineEntry[];expeditions:{active:ActiveExpedition;completed:CompletedExpedition[]};competitions:CompetitionRecord[];achievements:Achievement[];affiliations:{federation:string;providers:string[];machineClasses:string[]}}

/** Empty presentation state. Authenticated identity is loaded from Supabase; no production athlete is seeded in source code. */
export const passportData:PassportData={athlete:{name:"Athlete",initials:"A",country:"Not set",countryCode:"",city:"",cityIsOther:false,trainingContext:"Other",selectedClubId:"",customClub:{officialName:"",countryCode:"",country:"",city:"",website:"",federation:""},preferredMachineId:"unknown-model",memberSince:"",currentSeason:`${new Date().getFullYear()} season`,passportId:"",verificationStatus:"Unverified",completion:0,preferredMachine:"Not selected",biography:"",visibility:"Private"},summary:[{label:"Lifetime distance",value:"—",detail:"No persisted workouts yet"},{label:"Rowing time",value:"—",detail:"No persisted workouts yet"},{label:"Workouts",value:"0",detail:"Athlete-owned records"},{label:"Current rhythm",value:"—",detail:"Calculated from persisted workouts"},{label:"Personal bests",value:"0",detail:"No eligible results yet"},{label:"Expeditions",value:"0",detail:"No completed journeys"},{label:"Competition entries",value:"0",detail:"No persisted entries"},{label:"Verified results",value:"0",detail:"No verified results"}],personalBests:[],timeline:[],expeditions:{active:{name:"No active Expedition",subtitle:"Choose a journey when ready",currentPosition:"Not started",completedKm:0,totalKm:0,nextLandmark:"—",distanceToNextKm:0},completed:[]},competitions:[],achievements:[],affiliations:{federation:"No federation relationship declared",providers:[],machineClasses:[]}};
