export type WorkoutKind = "fixed-distance" | "fixed-time" | "interval";
export type SampleBasis = "per stroke" | "per second" | "per split" | "estimated" | "imported summary only";

export interface WorkoutMetrics { distanceMeters?:number; durationSeconds?:number; paceSecondsPer500?:number; averageWatts?:number; averageSpm?:number; calories?:number; strokeCount?:number; peakWatts?:number; averageHeartRate?:number; maximumHeartRate?:number }
export interface WorkoutSplit { id:string; number:number; distanceMeters?:number; durationSeconds:number; elapsedSeconds:number; paceSecondsPer500?:number; watts?:number; spm?:number; heartRate?:number; calories?:number }
export interface WorkoutInterval extends WorkoutSplit { segmentType:"work"|"recovery"|"warm-up"|"cool-down" }
export interface WorkoutSample { offsetSeconds:number; distanceMeters?:number; paceSecondsPer500?:number; watts?:number; spm?:number; heartRate?:number; resistance?:number }
export interface MachineDetail { brand:string; model:string; machineClass:string; monitor?:string; deviceId?:string; connectionMethod:string; dragFactor?:number; resistanceLevel?:number; damperSetting?:number; firmwareVersion?:string; comparability:"Same model ranking"|"Provider class ranking"|"Cross-provider comparable"|"Participation only"|"Not ranking eligible" }
export interface VerificationRecord { tier:number; label:string; authority:string; sourceProvider:string; importMethod:string; evidenceType:string; evidenceTimestamp:string; notes?:string; rankingEligible:boolean; exclusionReason?:string }
export interface ExpeditionContext { slug:string; name:string; contributedMeters:number; checkpoint:string; contributionDate:string; active:boolean }
export interface WorkoutRecord {
  id:string; athlete:{name:string;country:string;countryCode:string;affiliation:string}; title:string; resultType:string; kind:WorkoutKind; startedAt:string; timezone:string;
  metrics:WorkoutMetrics; machine:MachineDetail; verification:VerificationRecord; sourceMethod:string; sampleBasis:SampleBasis; samples:WorkoutSample[]; splits:WorkoutSplit[]; intervals:WorkoutInterval[];
  providerMetrics:Record<string,string|number|boolean>; notes?:string; coachNotes?:string; tags:string[]; perceivedExertion?:number; trainingPurpose?:string; visibility:"Private"|"Connections"|"Public";
  expedition?:ExpeditionContext; owner:boolean; attachments:{id:string;type:string;label:string}[];
}
export interface RankingContext { position?:number; eligibleCount:number; definition:string; division:string; ageCategory:string; weightCategory:string; adaptiveClassification?:string; geography:string; format:string; machineConstraints:string; verificationThreshold:string; personalBest:boolean; backQuery:string }
export interface EventContext { slug:string; eventName:string; organizer:string; race:string; stage?:string; lane?:string; bib?:string; position?:number; medal?:string; status:"Provisional"|"Verified"|"Disqualified"|"Appealed"|"Corrected"|"Official"; authority:string; registrationId:string }
export interface ResultRecord { id:string; workoutId?:string; athlete:{name:string;country:string;countryCode:string;affiliation:string}; resultType:string; rankingStatus:string; verification:VerificationRecord; ranking?:RankingContext; event?:EventContext; auditHistory:{id:string;at:string;action:string;actor:string}[] }

export const formatDuration=(seconds?:number)=>seconds==null?"Not recorded":`${Math.floor(seconds/60)}:${(seconds%60).toFixed(seconds%1?1:0).padStart(seconds%1?4:2,"0")}`;
export const formatPace=(seconds?:number)=>seconds==null?"Not recorded":formatDuration(seconds);
export const formatDistance=(meters?:number)=>meters==null?"Not recorded":`${meters.toLocaleString()} m`;

const athlete={name:"Mohamed Djebbari",country:"Algeria",countryCode:"DZ",affiliation:"Independent athlete"};
const c2:MachineDetail={brand:"Concept2",model:"RowErg",machineClass:"Static air resistance",monitor:"PM5",deviceId:"Hidden in public views",connectionMethod:"Concept2 Logbook import",dragFactor:125,damperSetting:5,firmwareVersion:"212",comparability:"Same model ranking"};
const providerVerification:VerificationRecord={tier:2,label:"Provider-imported",authority:"Concept2 authorized connection",sourceProvider:"Concept2 Logbook",importMethod:"Athlete-authorized cloud import",evidenceType:"Provider workout record",evidenceTimestamp:"2026-07-18T06:58:00+01:00",rankingEligible:true};
const split=(number:number,durationSeconds:number,watts:number,spm:number,heartRate:number):WorkoutSplit=>({id:`split-${number}`,number,distanceMeters:500,durationSeconds,elapsedSeconds:durationSeconds,paceSecondsPer500:durationSeconds,watts,spm,heartRate,calories:Math.round(durationSeconds*watts/4184)});
const splits2k=[split(1,110.4,259,27,152),split(2,109.8,264,28,161),split(3,109.6,266,28,169),split(4,108.9,271,30,176)].map((item,index,all)=>({...item,elapsedSeconds:all.slice(0,index+1).reduce((sum,row)=>sum+row.durationSeconds,0)}));
const telemetry:WorkoutSample[]=Array.from({length:15},(_,i)=>({offsetSeconds:i*30,distanceMeters:Math.min(2000,Math.round(i*143)),paceSecondsPer500:[112,110,109,111,110,109,110,109,111,110,109,108,110,108,106][i],watts:[248,260,267,254,261,268,260,267,254,261,268,274,260,274,290][i],spm:[26,27,28,27,28,28,28,29,28,28,29,29,29,30,32][i],heartRate:142+i*2}));

export const WORKOUT_RECORDS:WorkoutRecord[]=[
 {id:"workout-2k-provider",athlete,title:"Verified 2,000 m",resultType:"Personal best",kind:"fixed-distance",startedAt:"2026-07-18T06:42:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:2000,durationSeconds:438.7,paceSecondsPer500:109.675,averageWatts:263,averageSpm:28,calories:92,strokeCount:205,peakWatts:421,averageHeartRate:164,maximumHeartRate:178},machine:c2,verification:providerVerification,sourceMethod:"Provider import",sampleBasis:"per second",samples:telemetry,splits:splits2k,intervals:[],providerMetrics:{dragFactor:125,monitorType:"PM5",caloriesPerHour:754},notes:"Controlled first 1,500 m, then lifted through the finish.",tags:["2K","Personal best","Race preparation"],perceivedExertion:9,trainingPurpose:"Benchmark",visibility:"Public",owner:true,attachments:[{id:"att-1",type:"provider-record",label:"Original provider record"}],expedition:{slug:"danube",name:"The Danube",contributedMeters:2000,checkpoint:"Approaching Vienna",contributionDate:"18 July 2026",active:true}},
 {id:"workout-5k-training",athlete,title:"5,000 m aerobic training",resultType:"Training session",kind:"fixed-distance",startedAt:"2026-07-16T07:15:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:5000,durationSeconds:1241.6,paceSecondsPer500:124.16,averageWatts:181,averageSpm:23,calories:286,averageHeartRate:146},machine:c2,verification:providerVerification,sourceMethod:"Provider import",sampleBasis:"per split",samples:[],splits:Array.from({length:5},(_,i)=>({id:`5k-${i}`,number:i+1,distanceMeters:1000,durationSeconds:248.32,elapsedSeconds:248.32*(i+1),paceSecondsPer500:124.16,watts:181,spm:23,heartRate:140+i*3})),intervals:[],providerMetrics:{dragFactor:120},tags:["Aerobic","5K"],perceivedExertion:6,trainingPurpose:"Aerobic base",visibility:"Private",owner:true,attachments:[]},
 {id:"workout-30min-rp3",athlete,title:"Thirty-minute threshold",resultType:"Ranking-eligible result",kind:"fixed-time",startedAt:"2026-07-03T18:00:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:7214,durationSeconds:1800,paceSecondsPer500:124.76,averageWatts:178,averageSpm:25,calories:410},machine:{brand:"RP3",model:"Model S",machineClass:"Dynamic air resistance",monitor:"RP3 rowing software",connectionMethod:"Local device import",comparability:"Provider class ranking"},verification:{...providerVerification,authority:"RP3 trusted import",sourceProvider:"RP3",importMethod:"Local device file",evidenceType:"Signed workout export"},sourceMethod:"Provider import",sampleBasis:"per split",samples:[],splits:Array.from({length:6},(_,i)=>({id:`30m-${i}`,number:i+1,durationSeconds:300,elapsedSeconds:300*(i+1),distanceMeters:[1190,1198,1203,1205,1207,1211][i],paceSecondsPer500:[126.1,125.2,124.7,124.5,124.3,123.9][i],watts:178+i,spm:24+i%2})),intervals:[],providerMetrics:{dynamicStrokeLengthMeters:1.34},tags:["30 min","Threshold"],trainingPurpose:"Threshold benchmark",visibility:"Public",owner:true,attachments:[]},
 {id:"workout-interval-rp3",athlete,title:"6 × 500 m power intervals",resultType:"Training session",kind:"interval",startedAt:"2026-07-12T17:30:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:3000,durationSeconds:1180,averageWatts:302,averageSpm:31},machine:{brand:"RP3",model:"Model S",machineClass:"Dynamic air resistance",monitor:"RP3 rowing software",connectionMethod:"Bluetooth local capture",comparability:"Not ranking eligible"},verification:{...providerVerification,tier:3,label:"Device-attested",authority:"Paired RP3 device",sourceProvider:"RP3",importMethod:"Bluetooth capture"},sourceMethod:"Connected device",sampleBasis:"per split",samples:[],splits:[],intervals:Array.from({length:12},(_,i)=>({id:`int-${i}`,number:i+1,segmentType:i%2===0?"work":"recovery",distanceMeters:i%2===0?500:120,durationSeconds:i%2===0?105+i:90,elapsedSeconds:(i+1)*98,paceSecondsPer500:i%2===0?105+i:375,watts:i%2===0?310-i*2:55,spm:i%2===0?31:18,heartRate:150+i*2})),providerMetrics:{strokeLengthMeters:1.39},tags:["Intervals","Power"],perceivedExertion:8,trainingPurpose:"Power endurance",visibility:"Private",owner:true,attachments:[]},
 {id:"workout-water-participation",athlete,title:"10,000 m steady water row",resultType:"Expedition-linked workout",kind:"fixed-distance",startedAt:"2026-07-14T06:30:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:10000,durationSeconds:2538,paceSecondsPer500:126.9,averageSpm:22,calories:510},machine:{brand:"WaterRower",model:"Original Series",machineClass:"Water resistance",monitor:"S4",connectionMethod:"Manual photo entry",resistanceLevel:17,comparability:"Participation only"},verification:{tier:1,label:"Photo-confirmed",authority:"Rowform evidence review prototype",sourceProvider:"Manual",importMethod:"Photo upload",evidenceType:"Monitor photograph",evidenceTimestamp:"2026-07-14T07:15:00+01:00",rankingEligible:false,exclusionReason:"Water-resistance participation class is not eligible for this strict ranking."},sourceMethod:"Photo upload",sampleBasis:"imported summary only",samples:[],splits:[],intervals:[],providerMetrics:{waterTankLevel:17},tags:["Steady","Expedition"],trainingPurpose:"Endurance",visibility:"Connections",owner:true,attachments:[{id:"att-water",type:"photo",label:"Monitor photograph"}],expedition:{slug:"danube",name:"The Danube",contributedMeters:10000,checkpoint:"Linz reached",contributionDate:"14 July 2026",active:true}},
 {id:"workout-event-mvo",athlete,title:"Mediterranean Virtual Open 2,000 m",resultType:"Official competition result",kind:"fixed-distance",startedAt:"2026-06-20T18:10:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:2000,durationSeconds:438.7,paceSecondsPer500:109.675,averageWatts:263,averageSpm:28,calories:92},machine:c2,verification:{tier:4,label:"Organizer-verified",authority:"Rowform Events Lab prototype officials",sourceProvider:"Concept2 Logbook",importMethod:"Provider import plus organizer review",evidenceType:"Provider record and organizer decision",evidenceTimestamp:"2026-06-21T10:30:00Z",notes:"Official within the named prototype Event only.",rankingEligible:true},sourceMethod:"Provider import",sampleBasis:"per split",samples:telemetry,splits:splits2k,intervals:[],providerMetrics:{dragFactor:125},tags:["Event","2K"],trainingPurpose:"Competition",visibility:"Public",owner:true,attachments:[{id:"att-event",type:"event-evidence",label:"Organizer verification record"}]},
 {id:"workout-manual-summary",athlete,title:"Manual gym row",resultType:"Training session",kind:"fixed-distance",startedAt:"2026-07-09T07:05:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:5000,durationSeconds:1421},machine:{brand:"Unknown",model:"Not recorded",machineClass:"Unknown",connectionMethod:"Manual entry",comparability:"Not ranking eligible"},verification:{tier:0,label:"Manual",authority:"Athlete declaration",sourceProvider:"Manual",importMethod:"Manual entry",evidenceType:"None",evidenceTimestamp:"2026-07-09T07:40:00+01:00",rankingEligible:false,exclusionReason:"Machine and verification requirements are not met."},sourceMethod:"Manual entry",sampleBasis:"imported summary only",samples:[],splits:[],intervals:[],providerMetrics:{},notes:"Hotel gym session.",tags:["Travel"],visibility:"Private",owner:true,attachments:[]},
 {id:"workout-rp3-dynamic",athlete,title:"RP3 dynamic 2,000 m",resultType:"Ranking-eligible result",kind:"fixed-distance",startedAt:"2026-06-28T17:00:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:2000,durationSeconds:431.2,paceSecondsPer500:107.8,averageWatts:277,averageSpm:30},machine:{brand:"RP3",model:"Model T",machineClass:"Dynamic air resistance",monitor:"RP3 rowing software",connectionMethod:"Provider file",comparability:"Provider class ranking"},verification:{...providerVerification,sourceProvider:"RP3",authority:"RP3 trusted import"},sourceMethod:"Provider import",sampleBasis:"per split",samples:[],splits:[],intervals:[],providerMetrics:{strokeLengthMeters:1.42},tags:["2K"],visibility:"Public",owner:true,attachments:[]},
 {id:"workout-provider-telemetry",athlete,title:"Connected endurance row",resultType:"Training session",kind:"fixed-distance",startedAt:"2026-07-20T06:20:00+01:00",timezone:"Africa/Algiers",metrics:{distanceMeters:8000,durationSeconds:1990,paceSecondsPer500:124.4,averageWatts:180,averageSpm:23},machine:c2,verification:providerVerification,sourceMethod:"Provider import",sampleBasis:"per second",samples:telemetry,splits:[],intervals:[],providerMetrics:{dragFactor:118},tags:["Endurance"],visibility:"Private",owner:true,attachments:[]}
];

const rank:RankingContext={position:34,eligibleCount:284,definition:"2026 Men · Senior 23–39 · 2,000 m",division:"Men",ageCategory:"Senior 23–39",weightCategory:"Open weight",geography:"Algeria",format:"2,000 m · shortest elapsed time",machineConstraints:"Concept2 RowErg · static air resistance",verificationThreshold:"Tier 2 or higher",personalBest:true,backQuery:"scope=Country&country=DZ&season=2026&format=distance-2000&age=senior-23-39&division=men&weight=open-weight&brand=concept2&model=concept2-rowerg&machine=static-air-resistance&verification=all-accepted"};
export const RESULT_RECORDS:ResultRecord[]=[
 {id:"result-2k-pb",workoutId:"workout-2k-provider",athlete,resultType:"Personal best · ranking-eligible result",rankingStatus:"Eligible · position 34",verification:providerVerification,ranking:rank,auditHistory:[{id:"audit-1",at:"18 July 2026 · 07:02",action:"Imported and normalized",actor:"Concept2 adapter v1"},{id:"audit-2",at:"18 July 2026 · 07:05",action:"Ranking eligibility calculated",actor:"Rowform ranking rules v1"}]},
 {id:"result-30min-rp3",workoutId:"workout-30min-rp3",athlete,resultType:"Fixed-time ranking result",rankingStatus:"Provider-class eligible",verification:WORKOUT_RECORDS[2].verification,ranking:{...rank,position:12,eligibleCount:96,definition:"2026 Men · Senior 23–39 · 30 minutes",format:"30 minutes · greatest completed distance",machineConstraints:"RP3 dynamic class",personalBest:true,backQuery:"scope=Country&country=DZ&season=2026&format=time-30&age=senior-23-39&division=men&weight=open-weight&brand=rp3&machine=dynamic-air-resistance&verification=all-accepted"},auditHistory:[]},
 {id:"result-mvo-md-001",workoutId:"workout-event-mvo",athlete,resultType:"Official competition result",rankingStatus:"Organizer official · ranked",verification:WORKOUT_RECORDS[5].verification,ranking:{...rank,position:18,eligibleCount:146,definition:"Mediterranean Virtual Open · Men 30–39",geography:"Mediterranean region",personalBest:false},event:{slug:"mediterranean-virtual-open-2026",eventName:"Mediterranean Virtual Open",organizer:"Rowform Events Lab (prototype)",race:"2,000 m Individual",stage:"Final",lane:"Remote entry",bib:"MVO-018",position:18,status:"Official",authority:"Rowform Events Lab prototype officials",registrationId:"registration-mvo-md-001"},auditHistory:[{id:"event-audit-1",at:"21 June 2026 · 10:30 UTC",action:"Result declared official",actor:"Event organizer"}]},
 {id:"result-water-participation",workoutId:"workout-water-participation",athlete,resultType:"Participation result",rankingStatus:"Not ranking eligible",verification:WORKOUT_RECORDS[4].verification,auditHistory:[]},
 {id:"result-manual-summary",workoutId:"workout-manual-summary",athlete,resultType:"Athlete-declared result",rankingStatus:"Not ranking eligible",verification:WORKOUT_RECORDS[6].verification,auditHistory:[]}
];
export const workoutById=(id:string)=>WORKOUT_RECORDS.find((record)=>record.id===id);
export const resultById=(id:string)=>RESULT_RECORDS.find((record)=>record.id===id);

export function resolveResultView(id:string):{result:ResultRecord;workout:WorkoutRecord}|undefined{
 const stored=resultById(id); if(stored?.workoutId){const workout=workoutById(stored.workoutId);if(workout)return {result:stored,workout};}
 const event=EVENT_RESULTS.find((item)=>item.id===id); if(event){const template=workoutById("workout-event-mvo")!;return {result:{id:event.id,athlete:{name:event.athleteName,country:event.countryCode,countryCode:event.countryCode,affiliation:event.affiliation},resultType:"Event result",rankingStatus:event.status,verification:{...template.verification,label:event.verificationTier.replaceAll("-"," "),rankingEligible:event.status==="official"||event.status==="verified"},event:event.id==="result-mvo-md-001"?RESULT_RECORDS.find((r)=>r.id===event.id)?.event:undefined,auditHistory:[]},workout:{...template,id:`event-view-${event.id}`,athlete:{name:event.athleteName,country:event.countryCode,countryCode:event.countryCode,affiliation:event.affiliation},title:`${event.displayResult} · 2,000 m Event result`,metrics:{...template.metrics,durationSeconds:event.resultValue/1000,paceSecondsPer500:Number(event.pacePer500m.split(":")[0])*60+Number(event.pacePer500m.split(":")[1]),averageWatts:event.averageWatts,averageSpm:event.averageSpm},samples:[],splits:[],sampleBasis:"imported summary only",owner:false}};}
 const ranking=RANKING_RECORDS.find((item)=>item.id===id); if(ranking){const format=RANKING_FORMATS.find((item)=>item.id===ranking.formatId);const provider=getMachineProvider(ranking.providerId);const model=getMachineModel(ranking.modelId);const baseWorkout=workoutById(format?.kind==="fixed-time"?"workout-30min-rp3":"workout-manual-summary")!;const isTime=format?.kind==="fixed-time";return {result:{id:ranking.id,athlete:{name:ranking.athleteName,country:ranking.country,countryCode:ranking.countryCode,affiliation:ranking.club??"Independent athlete"},resultType:"Ranking result",rankingStatus:"Eligible in selected definition",verification:{...baseWorkout.verification,label:ranking.verificationId.replaceAll("-"," "),rankingEligible:true},ranking:{...rank,position:undefined,eligibleCount:RANKING_RECORDS.filter((r)=>r.formatId===ranking.formatId).length,definition:`${ranking.season} · ${format?.label??ranking.formatId}`,division:ranking.competitionDivisionId,ageCategory:ranking.ageCategoryId,weightCategory:ranking.weightCategoryId,geography:"Current filtered scope",format:format?.label??ranking.formatId,machineConstraints:`${provider?.displayName??"Unknown"} ${model?.model??""} · ${ranking.machineClassId}`,personalBest:false,backQuery:`season=${ranking.season}&format=${ranking.formatId}&age=${ranking.ageCategoryId}&division=${ranking.competitionDivisionId}&weight=${ranking.weightCategoryId}&brand=${ranking.providerId}&model=${ranking.modelId}&machine=${ranking.machineClassId}&verification=${ranking.verificationId}`},auditHistory:[]},workout:{...baseWorkout,id:`ranking-view-${ranking.id}`,athlete:{name:ranking.athleteName,country:ranking.country,countryCode:ranking.countryCode,affiliation:ranking.club??"Independent athlete"},title:`${format?.label??"Ranking"} · ${formatRankingResult(ranking)}`,resultType:"Ranking result",kind:isTime?"fixed-time":"fixed-distance",metrics:isTime?{durationSeconds:(format?.durationSeconds??60),distanceMeters:ranking.resultValue}:{distanceMeters:format?.distanceMeters,durationSeconds:ranking.resultValue/1000},machine:{...baseWorkout.machine,brand:provider?.displayName??"Unknown",model:model?.model??"Unknown",machineClass:ranking.machineClassId},verification:{...baseWorkout.verification,label:ranking.verificationId.replaceAll("-"," "),rankingEligible:true},samples:[],splits:[],intervals:[],sampleBasis:"imported summary only",owner:false}};}
 return stored?undefined:undefined;
}
import { EVENT_RESULTS } from "@/lib/events/data";
import { RANKING_RECORDS,formatRankingResult } from "@/lib/rankings/data";
import { RANKING_FORMATS } from "@/lib/competition-taxonomy";
import { getMachineModel,getMachineProvider } from "@/lib/machine-data";
