export interface CityOption {
  countryCode: string;
  name: string;
}

/**
 * Curated prototype cities: at least the administrative capital for inhabited ISO
 * territories, with broader coverage for major rowing markets. This is not a
 * complete global city database. “Other city” remains available for every country.
 */
export const CITIES: CityOption[] = [
  { countryCode: "AQ", name: "McMurdo Station" },
  { countryCode: "AF", name: "Kabul" },
  { countryCode: "AX", name: "Mariehamn" },
  { countryCode: "AL", name: "Tirana" },
  { countryCode: "DZ", name: "Algiers" },
  { countryCode: "DZ", name: "Oran" },
  { countryCode: "DZ", name: "Constantine" },
  { countryCode: "DZ", name: "Annaba" },
  { countryCode: "DZ", name: "Blida" },
  { countryCode: "AS", name: "Pago Pago" },
  { countryCode: "AD", name: "Andorra la Vella" },
  { countryCode: "AO", name: "Luanda" },
  { countryCode: "AI", name: "The Valley" },
  { countryCode: "AG", name: "Saint John's" },
  { countryCode: "AR", name: "Buenos Aires" },
  { countryCode: "AM", name: "Yerevan" },
  { countryCode: "AW", name: "Oranjestad" },
  { countryCode: "AU", name: "Canberra" },
  { countryCode: "AU", name: "Sydney" },
  { countryCode: "AU", name: "Melbourne" },
  { countryCode: "AU", name: "Brisbane" },
  { countryCode: "AU", name: "Perth" },
  { countryCode: "AU", name: "Adelaide" },
  { countryCode: "AT", name: "Vienna" },
  { countryCode: "AT", name: "Linz" },
  { countryCode: "AT", name: "Graz" },
  { countryCode: "AT", name: "Salzburg" },
  { countryCode: "AZ", name: "Baku" },
  { countryCode: "BS", name: "Nassau" },
  { countryCode: "BH", name: "Manama" },
  { countryCode: "BD", name: "Dhaka" },
  { countryCode: "BB", name: "Bridgetown" },
  { countryCode: "BY", name: "Minsk" },
  { countryCode: "BE", name: "Brussels" },
  { countryCode: "BZ", name: "Belmopan" },
  { countryCode: "BJ", name: "Porto-Novo" },
  { countryCode: "BM", name: "Hamilton" },
  { countryCode: "BT", name: "Thimphu" },
  { countryCode: "BO", name: "Sucre" },
  { countryCode: "BA", name: "Sarajevo" },
  { countryCode: "BW", name: "Gaborone" },
  { countryCode: "BR", name: "Brasília" },
  { countryCode: "IO", name: "Diego Garcia" },
  { countryCode: "VG", name: "Road Town" },
  { countryCode: "BN", name: "Bandar Seri Begawan" },
  { countryCode: "BG", name: "Sofia" },
  { countryCode: "BF", name: "Ouagadougou" },
  { countryCode: "BI", name: "Gitega" },
  { countryCode: "KH", name: "Phnom Penh" },
  { countryCode: "CM", name: "Yaoundé" },
  { countryCode: "CA", name: "Ottawa" },
  { countryCode: "CA", name: "Toronto" },
  { countryCode: "CA", name: "Vancouver" },
  { countryCode: "CA", name: "Montreal" },
  { countryCode: "CA", name: "Victoria" },
  { countryCode: "CA", name: "Calgary" },
  { countryCode: "CV", name: "Praia" },
  { countryCode: "BQ", name: "Kralendijk" },
  { countryCode: "KY", name: "George Town" },
  { countryCode: "CF", name: "Bangui" },
  { countryCode: "TD", name: "N'Djamena" },
  { countryCode: "CL", name: "Santiago" },
  { countryCode: "CN", name: "Beijing" },
  { countryCode: "CN", name: "Shanghai" },
  { countryCode: "CN", name: "Guangzhou" },
  { countryCode: "CN", name: "Shenzhen" },
  { countryCode: "CN", name: "Wuhan" },
  { countryCode: "CN", name: "Hangzhou" },
  { countryCode: "CX", name: "Flying Fish Cove" },
  { countryCode: "CC", name: "West Island" },
  { countryCode: "CO", name: "Bogotá" },
  { countryCode: "KM", name: "Moroni" },
  { countryCode: "CK", name: "Avarua" },
  { countryCode: "CR", name: "San José" },
  { countryCode: "HR", name: "Zagreb" },
  { countryCode: "CU", name: "Havana" },
  { countryCode: "CW", name: "Willemstad" },
  { countryCode: "CY", name: "Nicosia" },
  { countryCode: "CZ", name: "Prague" },
  { countryCode: "CZ", name: "Brno" },
  { countryCode: "CZ", name: "Ostrava" },
  { countryCode: "DK", name: "Copenhagen" },
  { countryCode: "DK", name: "Aarhus" },
  { countryCode: "DK", name: "Odense" },
  { countryCode: "DK", name: "Aalborg" },
  { countryCode: "DJ", name: "Djibouti" },
  { countryCode: "DM", name: "Roseau" },
  { countryCode: "DO", name: "Santo Domingo" },
  { countryCode: "CD", name: "Kinshasa" },
  { countryCode: "EC", name: "Quito" },
  { countryCode: "EG", name: "Cairo" },
  { countryCode: "SV", name: "San Salvador" },
  { countryCode: "GQ", name: "Malabo" },
  { countryCode: "ER", name: "Asmara" },
  { countryCode: "EE", name: "Tallinn" },
  { countryCode: "SZ", name: "Mbabane" },
  { countryCode: "ET", name: "Addis Ababa" },
  { countryCode: "FK", name: "Stanley" },
  { countryCode: "FO", name: "Tórshavn" },
  { countryCode: "FJ", name: "Suva" },
  { countryCode: "FI", name: "Helsinki" },
  { countryCode: "FR", name: "Paris" },
  { countryCode: "FR", name: "Lyon" },
  { countryCode: "FR", name: "Marseille" },
  { countryCode: "FR", name: "Bordeaux" },
  { countryCode: "FR", name: "Toulouse" },
  { countryCode: "FR", name: "Vichy" },
  { countryCode: "GF", name: "Cayenne" },
  { countryCode: "PF", name: "Papeetē" },
  { countryCode: "TF", name: "Port-aux-Français" },
  { countryCode: "GA", name: "Libreville" },
  { countryCode: "GM", name: "Banjul" },
  { countryCode: "GE", name: "Tbilisi" },
  { countryCode: "DE", name: "Berlin" },
  { countryCode: "DE", name: "Hamburg" },
  { countryCode: "DE", name: "Munich" },
  { countryCode: "DE", name: "Frankfurt" },
  { countryCode: "DE", name: "Cologne" },
  { countryCode: "DE", name: "Dresden" },
  { countryCode: "GH", name: "Accra" },
  { countryCode: "GI", name: "Gibraltar" },
  { countryCode: "GR", name: "Athens" },
  { countryCode: "GL", name: "Nuuk" },
  { countryCode: "GD", name: "St. George's" },
  { countryCode: "GP", name: "Basse-Terre" },
  { countryCode: "GU", name: "Hagåtña" },
  { countryCode: "GT", name: "Guatemala City" },
  { countryCode: "GG", name: "St. Peter Port" },
  { countryCode: "GN", name: "Conakry" },
  { countryCode: "GW", name: "Bissau" },
  { countryCode: "GY", name: "Georgetown" },
  { countryCode: "HT", name: "Port-au-Prince" },
  { countryCode: "HN", name: "Tegucigalpa" },
  { countryCode: "HK", name: "City of Victoria" },
  { countryCode: "HU", name: "Budapest" },
  { countryCode: "IS", name: "Reykjavik" },
  { countryCode: "IN", name: "New Delhi" },
  { countryCode: "ID", name: "Jakarta" },
  { countryCode: "IR", name: "Tehran" },
  { countryCode: "IQ", name: "Baghdad" },
  { countryCode: "IE", name: "Dublin" },
  { countryCode: "IE", name: "Cork" },
  { countryCode: "IE", name: "Galway" },
  { countryCode: "IE", name: "Limerick" },
  { countryCode: "IM", name: "Douglas" },
  { countryCode: "IL", name: "Jerusalem" },
  { countryCode: "IT", name: "Rome" },
  { countryCode: "IT", name: "Milan" },
  { countryCode: "IT", name: "Turin" },
  { countryCode: "IT", name: "Florence" },
  { countryCode: "IT", name: "Venice" },
  { countryCode: "IT", name: "Naples" },
  { countryCode: "CI", name: "Yamoussoukro" },
  { countryCode: "JM", name: "Kingston" },
  { countryCode: "JP", name: "Tokyo" },
  { countryCode: "JP", name: "Osaka" },
  { countryCode: "JP", name: "Kyoto" },
  { countryCode: "JP", name: "Yokohama" },
  { countryCode: "JP", name: "Nagoya" },
  { countryCode: "JE", name: "Saint Helier" },
  { countryCode: "JO", name: "Amman" },
  { countryCode: "KZ", name: "Nur-Sultan" },
  { countryCode: "KE", name: "Nairobi" },
  { countryCode: "KI", name: "South Tarawa" },
  { countryCode: "KW", name: "Kuwait City" },
  { countryCode: "KG", name: "Bishkek" },
  { countryCode: "LA", name: "Vientiane" },
  { countryCode: "LV", name: "Riga" },
  { countryCode: "LB", name: "Beirut" },
  { countryCode: "LS", name: "Maseru" },
  { countryCode: "LR", name: "Monrovia" },
  { countryCode: "LY", name: "Tripoli" },
  { countryCode: "LI", name: "Vaduz" },
  { countryCode: "LT", name: "Vilnius" },
  { countryCode: "LU", name: "Luxembourg" },
  { countryCode: "MG", name: "Antananarivo" },
  { countryCode: "MW", name: "Lilongwe" },
  { countryCode: "MY", name: "Kuala Lumpur" },
  { countryCode: "MV", name: "Malé" },
  { countryCode: "ML", name: "Bamako" },
  { countryCode: "MT", name: "Valletta" },
  { countryCode: "MH", name: "Majuro" },
  { countryCode: "MQ", name: "Fort-de-France" },
  { countryCode: "MR", name: "Nouakchott" },
  { countryCode: "MU", name: "Port Louis" },
  { countryCode: "YT", name: "Mamoudzou" },
  { countryCode: "MX", name: "Mexico City" },
  { countryCode: "FM", name: "Palikir" },
  { countryCode: "MD", name: "Chișinău" },
  { countryCode: "MC", name: "Monaco" },
  { countryCode: "MN", name: "Ulan Bator" },
  { countryCode: "ME", name: "Podgorica" },
  { countryCode: "MS", name: "Plymouth" },
  { countryCode: "MA", name: "Rabat" },
  { countryCode: "MZ", name: "Maputo" },
  { countryCode: "MM", name: "Naypyidaw" },
  { countryCode: "NA", name: "Windhoek" },
  { countryCode: "NR", name: "Yaren" },
  { countryCode: "NP", name: "Kathmandu" },
  { countryCode: "NL", name: "Amsterdam" },
  { countryCode: "NL", name: "Rotterdam" },
  { countryCode: "NL", name: "Utrecht" },
  { countryCode: "NL", name: "The Hague" },
  { countryCode: "NL", name: "Eindhoven" },
  { countryCode: "NC", name: "Nouméa" },
  { countryCode: "NZ", name: "Wellington" },
  { countryCode: "NZ", name: "Auckland" },
  { countryCode: "NZ", name: "Christchurch" },
  { countryCode: "NZ", name: "Hamilton" },
  { countryCode: "NZ", name: "Cambridge" },
  { countryCode: "NI", name: "Managua" },
  { countryCode: "NE", name: "Niamey" },
  { countryCode: "NG", name: "Abuja" },
  { countryCode: "NU", name: "Alofi" },
  { countryCode: "NF", name: "Kingston" },
  { countryCode: "KP", name: "Pyongyang" },
  { countryCode: "MK", name: "Skopje" },
  { countryCode: "MP", name: "Saipan" },
  { countryCode: "NO", name: "Oslo" },
  { countryCode: "NO", name: "Bergen" },
  { countryCode: "NO", name: "Trondheim" },
  { countryCode: "NO", name: "Stavanger" },
  { countryCode: "OM", name: "Muscat" },
  { countryCode: "PK", name: "Islamabad" },
  { countryCode: "PW", name: "Ngerulmud" },
  { countryCode: "PS", name: "Ramallah" },
  { countryCode: "PA", name: "Panama City" },
  { countryCode: "PG", name: "Port Moresby" },
  { countryCode: "PY", name: "Asunción" },
  { countryCode: "PE", name: "Lima" },
  { countryCode: "PH", name: "Manila" },
  { countryCode: "PN", name: "Adamstown" },
  { countryCode: "PL", name: "Warsaw" },
  { countryCode: "PL", name: "Kraków" },
  { countryCode: "PL", name: "Poznań" },
  { countryCode: "PL", name: "Wrocław" },
  { countryCode: "PL", name: "Gdańsk" },
  { countryCode: "PT", name: "Lisbon" },
  { countryCode: "PT", name: "Porto" },
  { countryCode: "PT", name: "Coimbra" },
  { countryCode: "PT", name: "Braga" },
  { countryCode: "PR", name: "San Juan" },
  { countryCode: "QA", name: "Doha" },
  { countryCode: "CG", name: "Brazzaville" },
  { countryCode: "RE", name: "Saint-Denis" },
  { countryCode: "RO", name: "Bucharest" },
  { countryCode: "RU", name: "Moscow" },
  { countryCode: "RW", name: "Kigali" },
  { countryCode: "BL", name: "Gustavia" },
  { countryCode: "SH", name: "Jamestown" },
  { countryCode: "KN", name: "Basseterre" },
  { countryCode: "LC", name: "Castries" },
  { countryCode: "MF", name: "Marigot" },
  { countryCode: "PM", name: "Saint-Pierre" },
  { countryCode: "VC", name: "Kingstown" },
  { countryCode: "WS", name: "Apia" },
  { countryCode: "SM", name: "City of San Marino" },
  { countryCode: "ST", name: "São Tomé" },
  { countryCode: "SA", name: "Riyadh" },
  { countryCode: "SA", name: "Jeddah" },
  { countryCode: "SA", name: "Dammam" },
  { countryCode: "SA", name: "Mecca" },
  { countryCode: "SA", name: "Medina" },
  { countryCode: "SN", name: "Dakar" },
  { countryCode: "RS", name: "Belgrade" },
  { countryCode: "SC", name: "Victoria" },
  { countryCode: "SL", name: "Freetown" },
  { countryCode: "SG", name: "Singapore" },
  { countryCode: "SX", name: "Philipsburg" },
  { countryCode: "SK", name: "Bratislava" },
  { countryCode: "SI", name: "Ljubljana" },
  { countryCode: "SB", name: "Honiara" },
  { countryCode: "SO", name: "Mogadishu" },
  { countryCode: "ZA", name: "Pretoria" },
  { countryCode: "ZA", name: "Cape Town" },
  { countryCode: "ZA", name: "Johannesburg" },
  { countryCode: "ZA", name: "Durban" },
  { countryCode: "GS", name: "King Edward Point" },
  { countryCode: "KR", name: "Seoul" },
  { countryCode: "SS", name: "Juba" },
  { countryCode: "ES", name: "Madrid" },
  { countryCode: "ES", name: "Barcelona" },
  { countryCode: "ES", name: "Seville" },
  { countryCode: "ES", name: "Valencia" },
  { countryCode: "ES", name: "Bilbao" },
  { countryCode: "LK", name: "Sri Jayawardenepura Kotte" },
  { countryCode: "SD", name: "Khartoum" },
  { countryCode: "SR", name: "Paramaribo" },
  { countryCode: "SJ", name: "Longyearbyen" },
  { countryCode: "SE", name: "Stockholm" },
  { countryCode: "SE", name: "Gothenburg" },
  { countryCode: "SE", name: "Malmö" },
  { countryCode: "SE", name: "Uppsala" },
  { countryCode: "CH", name: "Bern" },
  { countryCode: "CH", name: "Zurich" },
  { countryCode: "CH", name: "Geneva" },
  { countryCode: "CH", name: "Lausanne" },
  { countryCode: "CH", name: "Lucerne" },
  { countryCode: "SY", name: "Damascus" },
  { countryCode: "TW", name: "Taipei" },
  { countryCode: "TJ", name: "Dushanbe" },
  { countryCode: "TZ", name: "Dodoma" },
  { countryCode: "TH", name: "Bangkok" },
  { countryCode: "TL", name: "Dili" },
  { countryCode: "TG", name: "Lomé" },
  { countryCode: "TK", name: "Fakaofo" },
  { countryCode: "TO", name: "Nuku'alofa" },
  { countryCode: "TT", name: "Port of Spain" },
  { countryCode: "TN", name: "Tunis" },
  { countryCode: "TR", name: "Ankara" },
  { countryCode: "TM", name: "Ashgabat" },
  { countryCode: "TC", name: "Cockburn Town" },
  { countryCode: "TV", name: "Funafuti" },
  { countryCode: "UG", name: "Kampala" },
  { countryCode: "UA", name: "Kyiv" },
  { countryCode: "AE", name: "Abu Dhabi" },
  { countryCode: "GB", name: "London" },
  { countryCode: "GB", name: "Henley-on-Thames" },
  { countryCode: "GB", name: "Cambridge" },
  { countryCode: "GB", name: "Oxford" },
  { countryCode: "GB", name: "Nottingham" },
  { countryCode: "GB", name: "Glasgow" },
  { countryCode: "GB", name: "Edinburgh" },
  { countryCode: "US", name: "Washington, D.C." },
  { countryCode: "US", name: "Boston" },
  { countryCode: "US", name: "Cambridge" },
  { countryCode: "US", name: "New York" },
  { countryCode: "US", name: "Philadelphia" },
  { countryCode: "US", name: "Seattle" },
  { countryCode: "US", name: "San Francisco" },
  { countryCode: "US", name: "Austin" },
  { countryCode: "UM", name: "Washington DC" },
  { countryCode: "VI", name: "Charlotte Amalie" },
  { countryCode: "UY", name: "Montevideo" },
  { countryCode: "UZ", name: "Tashkent" },
  { countryCode: "VU", name: "Port Vila" },
  { countryCode: "VA", name: "Vatican City" },
  { countryCode: "VE", name: "Caracas" },
  { countryCode: "VN", name: "Hanoi" },
  { countryCode: "WF", name: "Mata-Utu" },
  { countryCode: "EH", name: "El Aaiún" },
  { countryCode: "YE", name: "Sana'a" },
  { countryCode: "ZM", name: "Lusaka" },
  { countryCode: "ZW", name: "Harare" },
  { countryCode: "MO", name: "Macau" },
];

export function citiesForCountry(countryCode: string) {
  return CITIES.filter((city) => city.countryCode === countryCode);
}
