import Link from "next/link";
import { ArrowRight, CalendarDays, MapPin, ShieldCheck, Ticket, Users } from "lucide-react";
import { commerceCta, eventOrganizer, eventPromotions, eventRaces, money } from "@/lib/events/data";
import type { EventDefinition } from "@/lib/events/types";

const verificationLabels={unverified:"Unverified listing",identity_checked:"Identity checked",organization_checked:"Organization checked",federation_verified:"Federation verified",platform_approved:"Platform approved"};
const date=(value:string)=>new Intl.DateTimeFormat("en",{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"}).format(new Date(value));

export function EventCard({event}:{event:EventDefinition}){
  const organizer=eventOrganizer(event); const races=eventRaces(event); const promotion=eventPromotions(event)[0]; const lowest=Math.min(...races.map((race)=>race.entryFeeMinor)); const remaining=races.map((race)=>race.remainingCapacity).filter((value):value is number=>typeof value==="number").reduce((sum,value)=>sum+value,0);
  return <article className="flex h-full min-w-0 flex-col overflow-hidden rounded-3xl border border-[#dfe5e1] bg-white shadow-[0_12px_35px_rgba(13,43,36,.06)]">
    <div className="relative bg-[#0d2b24] p-5 text-white sm:p-6"><div className="surface-grid absolute inset-0 opacity-30"/><div className="relative"><div className="flex flex-wrap items-center gap-2">{promotion&&<span className="rounded-full bg-[#ff6b35] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em]">{promotion.disclosureLabel}</span>}<span className="rounded-full border border-white/20 px-3 py-1 text-[10px] font-black uppercase tracking-[.12em]">{event.format}</span><span className="rounded-full border border-white/20 px-3 py-1 text-[10px] font-black uppercase tracking-[.12em]">{event.level}</span></div><h3 className="display-type mt-5 text-3xl font-black leading-tight">{event.title}</h3><p className="mt-2 text-sm leading-6 text-white/70">{event.summary}</p></div></div>
    <div className="flex flex-1 flex-col p-5 sm:p-6"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#e8f3ef] font-black text-[#0d2b24]">{event.logoText}</span><div><p className="text-sm font-black">{organizer.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-[#16725e]"><ShieldCheck size={13}/>{verificationLabels[organizer.verificationStatus]}</p></div></div>
      <dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div className="flex gap-2"><MapPin size={16} className="mt-0.5 shrink-0 text-[#d94d1c]"/><div><dt className="sr-only">Location</dt><dd className="font-bold">{event.city}, {event.country}</dd></div></div><div className="flex gap-2"><CalendarDays size={16} className="mt-0.5 shrink-0 text-[#d94d1c]"/><div><dt className="sr-only">Dates</dt><dd className="font-bold">{date(event.startsAt)}</dd></div></div><div className="flex gap-2"><Ticket size={16} className="mt-0.5 shrink-0 text-[#d94d1c]"/><div><dt className="sr-only">Entry price</dt><dd className="font-bold">{lowest?`From ${money(lowest,event.currency)}`:"Free / invite"}</dd></div></div><div className="flex gap-2"><Users size={16} className="mt-0.5 shrink-0 text-[#d94d1c]"/><div><dt className="sr-only">Capacity</dt><dd className="font-bold">{remaining?`${remaining} places left`:event.registrationStatus==="completed"?"Completed":"Capacity not published"}</dd></div></div></dl>
      <div className="mt-5 flex flex-wrap gap-2">{races.slice(0,3).map((race)=><span key={race.id} className="rounded-full bg-[#eef3f0] px-3 py-1.5 text-xs font-bold text-[#36534a]">{race.name}</span>)}</div><p className="mt-4 text-xs leading-5 text-[#718078]">{event.machineRuleSummary} · {event.verificationAuthority}</p>
      <div className="mt-auto pt-6"><Link href={`/events/${event.slug}`} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-full bg-[#ff6b35] px-5 text-sm font-black text-white hover:bg-[#e95b28] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0d2b24]">{commerceCta(event)} <ArrowRight size={16}/></Link></div>
    </div>
  </article>
}
