import type { ExpeditionDefinition } from "./types";
import { validateExpeditionCatalogue } from "./validate";

export const EXPEDITIONS: ExpeditionDefinition[] = [
  {
    slug: "nile", name: "The Nile", subtitle: "From the Great Lakes to the Mediterranean", region: "Africa", startLocation: "Jinja, Uganda", finishLocation: "Alexandria, Egypt", totalDistanceMeters: 6_650_000,
    countriesCrossed: ["Uganda", "South Sudan", "Sudan", "Egypt"], difficulty: "Epic", estimatedCompletionRange: "14–30 months",
    introduction: "Follow the White Nile north from the equatorial lakes, through vast wetlands and desert cities, until the river divides across its fertile delta. This is a patient journey through landscapes where water has sustained communities for millennia.",
    routeTheme: "Civilizations carried by water", cover: { from: "#082f32", to: "#b97b36", accent: "#f1c46b", motif: "papyrus channels" }, community: { participants: 3820, crews: 214, contributedMeters: 8_940_000_000 }, status: "recommended",
    completionReward: "Source-to-sea Nile medallion", certificateTitle: "The Nile — Great Lakes to Mediterranean",
    checkpoints: [
      { id: "nile-jinja", name: "Jinja", country: "Uganda", distanceMeters: 0, latitude: 0.4479, longitude: 33.2026, type: "start", story: "Your northbound journey begins where the Nile leaves Lake Victoria near Jinja.", context: "The source region connects East Africa's largest lake to the White Nile system.", reward: "Headwaters badge" },
      { id: "nile-juba", name: "Juba", country: "South Sudan", distanceMeters: 1_100_000, latitude: 4.8594, longitude: 31.5713, type: "city", story: "The river reaches Juba after crossing a greener, faster upper course.", context: "Juba stands beside a major transport corridor on the White Nile." },
      { id: "nile-sudd", name: "The Sudd", country: "South Sudan", distanceMeters: 1_750_000, latitude: 7.5, longitude: 30.5, type: "landmark", story: "Channels spread into one of the world's largest tropical wetlands.", context: "Seasonal water, reeds, and floating vegetation create a shifting inland landscape.", reward: "Wetlands explorer" },
      { id: "nile-khartoum", name: "Khartoum Confluence", country: "Sudan", distanceMeters: 3_100_000, latitude: 15.5007, longitude: 32.5599, type: "confluence", story: "Blue and White Nile waters meet at Khartoum and continue north as one river.", context: "The confluence links rainfall from the Ethiopian highlands with the Great Lakes system.", reward: "Two Niles achievement" },
      { id: "nile-luxor", name: "Luxor", country: "Egypt", distanceMeters: 4_950_000, latitude: 25.6872, longitude: 32.6396, type: "city", story: "The route enters a river corridor lined with monuments, fields, and living communities.", context: "Ancient Thebes developed around a Nile landscape that remains culturally significant." },
      { id: "nile-cairo", name: "Cairo", country: "Egypt", distanceMeters: 6_200_000, latitude: 30.0444, longitude: 31.2357, type: "city", story: "A vast modern city gathers around the river before the delta opens.", context: "Cairo has long connected Upper Egypt, the delta, and Mediterranean trade." },
      { id: "nile-alexandria", name: "Alexandria", country: "Egypt", distanceMeters: 6_650_000, latitude: 31.2001, longitude: 29.9187, type: "finish", story: "You reach the Mediterranean beside Alexandria after rowing the length of a continental story.", context: "The port city faces the sea at the western edge of the Nile Delta.", reward: "Nile finisher" },
    ],
  },
  {
    slug: "danube", name: "The Danube", subtitle: "Ten countries, one eastbound current", region: "Europe", startLocation: "Donaueschingen, Germany", finishLocation: "Sulina, Romania", totalDistanceMeters: 2_850_000,
    countriesCrossed: ["Germany", "Austria", "Slovakia", "Hungary", "Croatia", "Serbia", "Bulgaria", "Romania", "Moldova", "Ukraine"], difficulty: "Endurance", estimatedCompletionRange: "7–14 months",
    introduction: "Leave the Black Forest and row east through imperial capitals, border reaches, limestone gorges, and the reed beds of the Black Sea Delta. The Danube is Europe's great shared corridor.",
    routeTheme: "A river without a single nation", cover: { from: "#092e3c", to: "#235f73", accent: "#ff8055", motif: "continental bends" }, community: { participants: 1842, crews: 126, contributedMeters: 2_130_000_000 }, status: "active",
    completionReward: "Danube ten-country route patch", certificateTitle: "The Danube — Black Forest to Black Sea",
    checkpoints: [
      { id: "danube-source", name: "Donaueschingen", country: "Germany", distanceMeters: 0, latitude: 47.953, longitude: 8.503, type: "start", story: "Begin at the meeting of headwater streams on the edge of the Black Forest.", context: "The traditional Danube source marks the start of Europe's second-longest river.", reward: "Black Forest launch" },
      { id: "danube-ulm", name: "Ulm", country: "Germany", distanceMeters: 258_000, latitude: 48.4011, longitude: 9.9876, type: "city", story: "The young river becomes a working waterway beneath Ulm's skyline.", context: "Historic river craft once carried goods downstream from this Swabian city." },
      { id: "danube-passau", name: "Passau", country: "Germany", distanceMeters: 590_000, latitude: 48.5667, longitude: 13.4319, type: "confluence", story: "Three rivers meet in Passau, widening the journey before Austria.", context: "The Danube, Inn, and Ilz converge here with visibly different water conditions.", reward: "Three Rivers badge" },
      { id: "danube-vienna", name: "Vienna", country: "Austria", distanceMeters: 650_000, latitude: 48.2082, longitude: 16.3738, type: "city", story: "Row past an international capital shaped by trade, music, and the river's floodplain.", context: "Vienna's Danube channels host recreation, transport, and rowing communities." },
      { id: "danube-budapest", name: "Budapest", country: "Hungary", distanceMeters: 930_000, latitude: 47.4979, longitude: 19.0402, type: "city", story: "Buda and Pest face one another across a broad ceremonial reach.", context: "Bridges bind the two banks into one capital and frame the river's urban passage.", reward: "Twin Cities marker" },
      { id: "danube-belgrade", name: "Belgrade", country: "Serbia", distanceMeters: 1_370_000, latitude: 44.7866, longitude: 20.4489, type: "confluence", story: "The Sava joins the Danube below Belgrade's fortress ridge.", context: "This confluence has been a strategic meeting point between regions and cultures." },
      { id: "danube-iron-gates", name: "Iron Gates", country: "Serbia / Romania", distanceMeters: 1_560_000, latitude: 44.67, longitude: 22.53, type: "landmark", story: "The river narrows through a dramatic gorge between the Carpathians and Balkans.", context: "Navigation works transformed this once-dangerous passage while preserving its scale.", reward: "Gorge passage" },
      { id: "danube-delta", name: "Sulina", country: "Romania", distanceMeters: 2_850_000, latitude: 45.155, longitude: 29.654, type: "finish", story: "Reed channels open toward the Black Sea at the end of a ten-country crossing.", context: "The Danube Delta is a vast wetland mosaic important to migratory birds.", reward: "Black Sea finisher" },
    ],
  },
  {
    slug: "rhine", name: "The Rhine", subtitle: "Alpine water to the North Sea", region: "Europe", startLocation: "Lake Toma, Switzerland", finishLocation: "Rotterdam, Netherlands", totalDistanceMeters: 1_230_000,
    countriesCrossed: ["Switzerland", "Liechtenstein", "Austria", "Germany", "France", "Netherlands"], difficulty: "Moderate", estimatedCompletionRange: "3–7 months",
    introduction: "Trace the Rhine from a high Alpine source through lake country, border cities, vineyard gorges, and Europe's busiest delta. Castles and cargo share the same long current.", routeTheme: "Alpine source to industrial artery", cover: { from: "#183c45", to: "#647b66", accent: "#d8e7b2", motif: "ridge and current" }, community: { participants: 2310, crews: 141, contributedMeters: 1_845_000_000 }, status: "recommended", completionReward: "Rhine source-to-sea enamel crest", certificateTitle: "The Rhine — Alps to North Sea",
    checkpoints: [
      { id: "rhine-toma", name: "Lake Toma", country: "Switzerland", distanceMeters: 0, latitude: 46.632, longitude: 8.672, type: "start", story: "The route begins beside a small Alpine lake beneath steep slopes.", context: "Lake Toma is traditionally identified as a source of the anterior Rhine.", reward: "Alpine source" },
      { id: "rhine-bodensee", name: "Lake Constance", country: "Switzerland / Germany", distanceMeters: 250_000, latitude: 47.63, longitude: 9.37, type: "border", story: "The young Rhine enters a broad lake shared by three countries.", context: "Lake Constance creates an international waterscape with a strong rowing culture." },
      { id: "rhine-basel", name: "Basel", country: "Switzerland", distanceMeters: 380_000, latitude: 47.5596, longitude: 7.5886, type: "city", story: "At Basel the river turns decisively north toward the Upper Rhine.", context: "The city is a major cultural and transport gateway at a three-country region." },
      { id: "rhine-strasbourg", name: "Strasbourg", country: "France", distanceMeters: 520_000, latitude: 48.5734, longitude: 7.7521, type: "city", story: "Canals and European institutions meet the Rhine's border landscape.", context: "The river has alternately divided and connected France and Germany." },
      { id: "rhine-lorelei", name: "Lorelei Reach", country: "Germany", distanceMeters: 780_000, latitude: 50.139, longitude: 7.731, type: "landmark", story: "Vineyards and castle ridges close around a famous narrow passage.", context: "Currents and rock once made this Middle Rhine reach especially demanding.", reward: "Gorge navigator" },
      { id: "rhine-cologne", name: "Cologne", country: "Germany", distanceMeters: 920_000, latitude: 50.9375, longitude: 6.9603, type: "city", story: "The river widens beneath Cologne's bridges and cathedral skyline.", context: "Cologne has used the Rhine as a civic and commercial axis since Roman times." },
      { id: "rhine-rotterdam", name: "Rotterdam", country: "Netherlands", distanceMeters: 1_230_000, latitude: 51.9244, longitude: 4.4777, type: "finish", story: "Delta channels carry the journey into one of the world's great port landscapes.", context: "The Rhine–Meuse delta connects inland Europe to the North Sea.", reward: "North Sea arrival" },
    ],
  },
  {
    slug: "thames", name: "The Thames", subtitle: "From Cotswold meadows to the tideway", region: "Europe", startLocation: "Thames Head, England", finishLocation: "Thames Estuary, England", totalDistanceMeters: 346_000,
    countriesCrossed: ["United Kingdom"], difficulty: "Accessible", estimatedCompletionRange: "3–8 weeks", introduction: "Begin among quiet Cotswold fields, pass university boathouses and royal reaches, then join the tide through London. This compact journey follows a river inseparable from rowing history.", routeTheme: "The home water of modern rowing", cover: { from: "#17372f", to: "#6a785f", accent: "#ff7750", motif: "tideway lanes" }, community: { participants: 6240, crews: 318, contributedMeters: 3_410_000_000 }, status: "completed", completionReward: "Tideway finisher pennant", certificateTitle: "The Thames — Source to Tideway",
    checkpoints: [
      { id: "thames-head", name: "Thames Head", country: "United Kingdom", distanceMeters: 0, latitude: 51.694, longitude: -2.03, type: "start", story: "Set off from seasonal springs in the Cotswold countryside.", context: "The river begins modestly before gathering tributaries across southern England.", reward: "Source marker" },
      { id: "thames-oxford", name: "Oxford", country: "United Kingdom", distanceMeters: 105_000, latitude: 51.752, longitude: -1.2577, type: "city", story: "Boathouses and college crews bring the river's rowing identity into view.", context: "Oxford's stretches support long traditions of collegiate racing and training." },
      { id: "thames-henley", name: "Henley-on-Thames", country: "United Kingdom", distanceMeters: 185_000, latitude: 51.536, longitude: -0.902, type: "landmark", story: "The route passes a town known internationally for rowing competition.", context: "Henley Royal Regatta has shaped the river's sporting reputation since the nineteenth century.", reward: "Regatta reach" },
      { id: "thames-windsor", name: "Windsor", country: "United Kingdom", distanceMeters: 230_000, latitude: 51.4817, longitude: -0.6044, type: "city", story: "A royal skyline rises above a gentler middle reach.", context: "The river has long linked settlements, estates, and trade west of London." },
      { id: "thames-putney", name: "Putney", country: "United Kingdom", distanceMeters: 285_000, latitude: 51.466, longitude: -0.215, type: "landmark", story: "Enter the Tideway at one of rowing's most recognizable urban starts.", context: "Putney is the start area for the annual Oxford–Cambridge Boat Race." },
      { id: "thames-greenwich", name: "Greenwich", country: "United Kingdom", distanceMeters: 322_000, latitude: 51.4826, longitude: -0.0077, type: "city", story: "Maritime history and modern London meet on a broad tidal bend.", context: "Greenwich is associated with navigation, timekeeping, and Britain's maritime story." },
      { id: "thames-estuary", name: "Thames Estuary", country: "United Kingdom", distanceMeters: 346_000, latitude: 51.5, longitude: 0.65, type: "finish", story: "The city falls behind as tidal water opens toward the North Sea.", context: "Mudflats, marshes, ports, and channels define the river's final landscape.", reward: "Tideway complete" },
    ],
  },
  {
    slug: "mississippi", name: "The Mississippi", subtitle: "America's river from north woods to delta", region: "North America", startLocation: "Lake Itasca, Minnesota", finishLocation: "Head of Passes, Louisiana", totalDistanceMeters: 3_730_000,
    countriesCrossed: ["United States"], difficulty: "Endurance", estimatedCompletionRange: "9–18 months", introduction: "Leave a small northern lake and follow a river that becomes an immense transport corridor. Cities, confluences, levees, music, agriculture, and wetlands mark the long descent to the Gulf.", routeTheme: "A continental gathering river", cover: { from: "#172c36", to: "#78563d", accent: "#f0b35f", motif: "delta branches" }, community: { participants: 2980, crews: 166, contributedMeters: 4_820_000_000 }, status: "available", completionReward: "Great River passage medal", certificateTitle: "The Mississippi — Itasca to the Gulf",
    checkpoints: [
      { id: "miss-itaska", name: "Lake Itasca", country: "United States", distanceMeters: 0, latitude: 47.239, longitude: -95.207, type: "start", story: "Step across the narrow headwaters before beginning the southbound route.", context: "Lake Itasca is conventionally recognized as the Mississippi's source.", reward: "Headwaters crossing" },
      { id: "miss-twin-cities", name: "Twin Cities", country: "United States", distanceMeters: 740_000, latitude: 44.9778, longitude: -93.265, type: "city", story: "The river enters Minneapolis and Saint Paul through locks, falls, and bluffs.", context: "Water power and navigation shaped the growth of both cities." },
      { id: "miss-st-louis", name: "St. Louis", country: "United States", distanceMeters: 1_900_000, latitude: 38.627, longitude: -90.1994, type: "confluence", story: "The Missouri joins just upstream as the route reaches the Gateway City.", context: "The combined watershed drains a vast portion of North America.", reward: "Great confluence" },
      { id: "miss-memphis", name: "Memphis", country: "United States", distanceMeters: 2_550_000, latitude: 35.1495, longitude: -90.049, type: "city", story: "High bluffs overlook a river tied to trade and a globally influential music culture.", context: "Memphis grew as a major port on the Lower Mississippi." },
      { id: "miss-vicksburg", name: "Vicksburg", country: "United States", distanceMeters: 3_000_000, latitude: 32.3526, longitude: -90.8779, type: "landmark", story: "Levees and engineered bends reveal how people have reshaped the river.", context: "Vicksburg occupies a commanding position in the river's military and transport history." },
      { id: "miss-new-orleans", name: "New Orleans", country: "United States", distanceMeters: 3_570_000, latitude: 29.9511, longitude: -90.0715, type: "city", story: "The crescent bend carries you through a port city of layered cultures and sound.", context: "The city links the inland river network with global maritime routes." },
      { id: "miss-gulf", name: "Head of Passes", country: "United States", distanceMeters: 3_730_000, latitude: 29.15, longitude: -89.25, type: "finish", story: "The main channel divides across wetlands before meeting the Gulf of Mexico.", context: "Delta land is created and continually reshaped by sediment, storms, and engineering.", reward: "Gulf arrival" },
    ],
  },
  {
    slug: "amazon", name: "The Amazon", subtitle: "Across the world's largest river system", region: "South America", startLocation: "Andean headwaters, Peru", finishLocation: "Atlantic coast, Brazil", totalDistanceMeters: 6_400_000,
    countriesCrossed: ["Peru", "Colombia", "Brazil"], difficulty: "Epic", estimatedCompletionRange: "14–30 months", introduction: "Descend from cold Andean headwaters into a river system of extraordinary scale. Flooded forests, remote communities, immense tributaries, and a tidal Atlantic mouth make every stage feel different.", routeTheme: "Water, forest, and planetary scale", cover: { from: "#092f28", to: "#25694e", accent: "#e5ce69", motif: "flooded forest" }, community: { participants: 3410, crews: 207, contributedMeters: 7_320_000_000 }, status: "recommended", completionReward: "Amazon watershed guardian emblem", certificateTitle: "The Amazon — Andes to Atlantic",
    checkpoints: [
      { id: "amazon-andes", name: "Andean Headwaters", country: "Peru", distanceMeters: 0, latitude: -15.5, longitude: -71.7, type: "start", story: "Begin among high valleys where small streams start their long descent east.", context: "Several headwater definitions exist; this route uses a curated symbolic start rather than claiming a single uncontested source.", reward: "High Andes launch" },
      { id: "amazon-iquitos", name: "Iquitos", country: "Peru", distanceMeters: 1_350_000, latitude: -3.7437, longitude: -73.2516, type: "city", story: "The route reaches a major city connected to the wider world primarily by river and air.", context: "Iquitos sits within a vast lowland network of channels and floodplain forest." },
      { id: "amazon-triple", name: "Three Frontiers", country: "Peru / Colombia / Brazil", distanceMeters: 1_800_000, latitude: -4.22, longitude: -69.94, type: "border", story: "Three countries meet around the river near Leticia, Tabatinga, and Santa Rosa.", context: "The frontier shows how the river connects communities across political borders.", reward: "Three Frontiers badge" },
      { id: "amazon-tefe", name: "Tefé", country: "Brazil", distanceMeters: 3_050_000, latitude: -3.353, longitude: -64.711, type: "landmark", story: "Broad water and protected floodplain landscapes define the middle journey.", context: "Nearby reserves protect seasonal forests and habitats shaped by changing water levels." },
      { id: "amazon-manaus", name: "Meeting of Waters", country: "Brazil", distanceMeters: 4_050_000, latitude: -3.135, longitude: -59.905, type: "confluence", story: "Dark Rio Negro water runs beside the sediment-rich Solimões before the currents blend.", context: "Differences in temperature, speed, and sediment keep the waters visibly distinct for kilometres.", reward: "Meeting of Waters" },
      { id: "amazon-santarem", name: "Santarém", country: "Brazil", distanceMeters: 5_200_000, latitude: -2.4385, longitude: -54.6996, type: "confluence", story: "Another striking meeting of waters opens beside the Tapajós.", context: "Clearer tributary water meets the main river near a city with deep Indigenous and colonial histories." },
      { id: "amazon-belem", name: "Belém and the Atlantic", country: "Brazil", distanceMeters: 6_400_000, latitude: -1.4558, longitude: -48.4902, type: "finish", story: "Tides, islands, and distributaries carry the expedition into the Atlantic world.", context: "The Amazon mouth is a complex estuarine region rather than a single simple channel.", reward: "Atlantic forest finisher" },
    ],
  },
  {
    slug: "mekong", name: "The Mekong", subtitle: "High plateau to nine-dragon delta", region: "Asia", startLocation: "Tibetan Plateau", finishLocation: "Mekong Delta, Vietnam", totalDistanceMeters: 4_350_000,
    countriesCrossed: ["China", "Myanmar", "Laos", "Thailand", "Cambodia", "Vietnam"], difficulty: "Epic", estimatedCompletionRange: "10–22 months", introduction: "Travel from high Asian headwaters through mountain gorges, border reaches, ancient cities, and one of the world's most productive deltas. The Mekong is a shared lifeline with many names.", routeTheme: "Six countries and a living flood pulse", cover: { from: "#15313a", to: "#776137", accent: "#ff8a58", motif: "terraces and delta" }, community: { participants: 1760, crews: 94, contributedMeters: 2_360_000_000 }, status: "available", completionReward: "Nine Dragons route emblem", certificateTitle: "The Mekong — Plateau to Delta",
    checkpoints: [
      { id: "mekong-plateau", name: "Tibetan Plateau", country: "China", distanceMeters: 0, latitude: 33.7, longitude: 94.7, type: "start", story: "Begin high on the plateau where the river is known as the Lancang Jiang downstream.", context: "Snowmelt and highland tributaries feed a river that crosses several climate zones.", reward: "High plateau start" },
      { id: "mekong-yunnan", name: "Yunnan Gorges", country: "China", distanceMeters: 950_000, latitude: 25.0, longitude: 100.2, type: "landmark", story: "Deep valleys funnel the river south through a biologically diverse province.", context: "The upper basin's steep gradients contrast sharply with the later floodplain." },
      { id: "mekong-golden", name: "Golden Triangle", country: "Laos / Thailand / Myanmar", distanceMeters: 1_750_000, latitude: 20.35, longitude: 100.08, type: "border", story: "Three national frontiers meet around a broad river bend.", context: "The region has long been a crossroads for trade, migration, and contested histories.", reward: "Three-border crossing" },
      { id: "mekong-luang", name: "Luang Prabang", country: "Laos", distanceMeters: 2_150_000, latitude: 19.8833, longitude: 102.1333, type: "city", story: "Mountain ridges frame a historic city at the meeting of the Mekong and Nam Khan.", context: "The river remains central to daily movement, ceremony, and local livelihoods." },
      { id: "mekong-phnom", name: "Phnom Penh", country: "Cambodia", distanceMeters: 3_400_000, latitude: 11.5564, longitude: 104.9282, type: "confluence", story: "The Mekong, Tonlé Sap, and Bassac form a dynamic water junction.", context: "Seasonal flow reversal in the Tonlé Sap system supports fisheries and floodplain agriculture." },
      { id: "mekong-cantho", name: "Cần Thơ", country: "Vietnam", distanceMeters: 4_050_000, latitude: 10.0452, longitude: 105.7469, type: "city", story: "Markets, canals, orchards, and dense settlement signal the great delta.", context: "The Vietnamese name Cửu Long evokes the river's many distributary 'dragons'." },
      { id: "mekong-delta", name: "South China Sea", country: "Vietnam", distanceMeters: 4_350_000, latitude: 9.55, longitude: 106.3, type: "finish", story: "Multiple channels complete the passage through a low, fertile, vulnerable coast.", context: "The delta supports millions of people while facing salinity, subsidence, and changing flows.", reward: "Nine Dragons finisher" },
    ],
  },
  {
    slug: "murray", name: "The Murray", subtitle: "Snow country to the Southern Ocean", region: "Oceania", startLocation: "Australian Alps", finishLocation: "Murray Mouth, South Australia", totalDistanceMeters: 2_508_000,
    countriesCrossed: ["Australia"], difficulty: "Endurance", estimatedCompletionRange: "6–13 months", introduction: "Follow Australia's longest river from alpine country through red-gum forests, farming towns, wetlands, and lakes. The journey explores a living cultural landscape under constant pressure from water use and climate.", routeTheme: "An inland river sustaining a dry continent", cover: { from: "#263b39", to: "#a26944", accent: "#f2d08a", motif: "red-gum bends" }, community: { participants: 1420, crews: 82, contributedMeters: 1_620_000_000 }, status: "available", completionReward: "Murray river-country insignia", certificateTitle: "The Murray — Alps to Ocean",
    checkpoints: [
      { id: "murray-alps", name: "Australian Alps", country: "Australia", distanceMeters: 0, latitude: -36.47, longitude: 148.2, type: "start", story: "Begin where mountain streams gather beneath the high country.", context: "Alpine rainfall and snowmelt feed the upper Murray and its tributaries.", reward: "High country launch" },
      { id: "murray-albury", name: "Albury–Wodonga", country: "Australia", distanceMeters: 330_000, latitude: -36.0737, longitude: 146.9135, type: "border", story: "Twin cities face one another across a river that forms much of a state boundary.", context: "The Murray links New South Wales and Victoria while serving both communities." },
      { id: "murray-echuca", name: "Echuca", country: "Australia", distanceMeters: 820_000, latitude: -36.1406, longitude: 144.7519, type: "city", story: "Historic river-port country recalls the era of paddle-steamer trade.", context: "Echuca became a major nineteenth-century transfer point for wool and supplies.", reward: "River-port badge" },
      { id: "murray-mildura", name: "Mildura", country: "Australia", distanceMeters: 1_460_000, latitude: -34.208, longitude: 142.1246, type: "city", story: "Irrigated orchards and a dry inland climate meet along a broad reach.", context: "Water management here reveals both the value and complexity of basin agriculture." },
      { id: "murray-wentworth", name: "Darling Confluence", country: "Australia", distanceMeters: 1_600_000, latitude: -34.107, longitude: 141.914, type: "confluence", story: "The Darling joins at Wentworth, connecting an enormous inland basin.", context: "Flows from distant northern catchments can take months to reach this confluence." },
      { id: "murray-riverland", name: "Riverland", country: "Australia", distanceMeters: 2_050_000, latitude: -34.25, longitude: 140.47, type: "landmark", story: "Cliffs, wetlands, and river red gums accompany the final western stages.", context: "Wetland habitats depend on variable flows and careful environmental management." },
      { id: "murray-mouth", name: "Murray Mouth", country: "Australia", distanceMeters: 2_508_000, latitude: -35.556, longitude: 138.88, type: "finish", story: "Lakes and lagoon country lead to a narrow opening onto the Southern Ocean.", context: "The Coorong and Lower Lakes form a culturally and ecologically significant system.", reward: "Southern Ocean finisher" },
    ],
  },
];

export function getExpedition(slug: string) {
  return EXPEDITIONS.find((expedition) => expedition.slug === slug);
}

const catalogueErrors = validateExpeditionCatalogue(EXPEDITIONS);
if (catalogueErrors.length > 0) {
  throw new Error(`Invalid Expedition catalogue:\n${catalogueErrors.join("\n")}`);
}
