import type { EventDefinition, EventNotice, EventPromotion, EventResult, EventSource, FeeBreakdown, FeeConfiguration, Organizer, PaymentRecord, Race, Registration, Waiver } from "./types";

export const CURRENT_ATHLETE = { id: "athlete-md-001", name: "Mohamed Djebbari", passportId: "RF-DZ-MD-7K2P", country: "Algeria", ageCategoryId: "senior-23-39", affiliation: "independent" as const };

export const ORGANIZERS: Organizer[] = [
  { id:"org-rowform-events",name:"Rowform Events Lab",type:"event_organizer",contactEmail:"events@rowform.test",supportContact:"Prototype event support",website:"https://example.com/rowform-events",billingProfileStatus:"prototype",verificationStatus:"platform_approved",ownershipStatus:"rowform_managed",payoutAccountStatus:"not_configured",commercialAgreementStatus:"prototype",worldRowingAffiliationVerified:false,authorizedAdministratorIds:["admin-prototype-1"] },
  { id:"org-atlas-club",name:"Atlas Rowing Club (prototype)",type:"club",contactEmail:"events@atlas-rowing.example",supportContact:"Club events team",billingProfileStatus:"prototype",verificationStatus:"organization_checked",ownershipStatus:"verified_organizer_owned",payoutAccountStatus:"pending",commercialAgreementStatus:"draft",federationAffiliation:"Prototype national federation relationship",worldRowingAffiliationVerified:false,authorizedAdministratorIds:[] },
  { id:"org-north-university",name:"North Harbour University Rowing (prototype)",type:"university",contactEmail:"sport@northharbour.example",supportContact:"University sport office",billingProfileStatus:"not_configured",verificationStatus:"identity_checked",ownershipStatus:"claimed_by_organizer",payoutAccountStatus:"not_configured",commercialAgreementStatus:"none",worldRowingAffiliationVerified:false,authorizedAdministratorIds:[] },
  { id:"org-national-demo",name:"National Indoor Rowing Federation Demo",type:"national_federation",contactEmail:"indoor@national-demo.example",supportContact:"Championship office",billingProfileStatus:"prototype",verificationStatus:"federation_verified",ownershipStatus:"verified_organizer_owned",payoutAccountStatus:"pending",commercialAgreementStatus:"draft",federationAffiliation:"Fictional demonstration federation",worldRowingAffiliationVerified:false,authorizedAdministratorIds:[] },
  { id:"org-continental-demo",name:"Continental Indoor Rowing Council (prototype)",type:"continental_body",contactEmail:"events@continental-demo.example",supportContact:"Competition secretariat",billingProfileStatus:"not_configured",verificationStatus:"organization_checked",ownershipStatus:"unclaimed_public_listing",payoutAccountStatus:"not_configured",commercialAgreementStatus:"none",worldRowingAffiliationVerified:false,authorizedAdministratorIds:[] },
  { id:"org-global-demo",name:"Global Indoor Rowing Assembly (prototype)",type:"international_body",contactEmail:"competition@global-demo.example",supportContact:"International event desk",billingProfileStatus:"not_configured",verificationStatus:"organization_checked",ownershipStatus:"unclaimed_public_listing",payoutAccountStatus:"not_configured",commercialAgreementStatus:"none",worldRowingAffiliationVerified:false,authorizedAdministratorIds:[] },
];

export const RACES: Race[] = [
  { id:"race-mvo-2k",eventId:"event-mvo-2026",name:"2,000 m Individual",formatId:"distance-2000",distanceMeters:2000,divisions:["men","women","lightweight-men","lightweight-women"],ageCategoryIds:["u23","senior-23-39","masters-40-44","masters-45-49"],weightCategoryIds:["open-weight","lightweight"],adaptiveClassificationIds:[],machineProviderIds:["concept2"],machineClassIds:["static-air-resistance"],verificationRequirement:"organizer-verified",rankingDefinitionId:"ranking-mvo-2026-2k",scoring:"elapsed_time_ascending",medals:["Gold","Silver","Bronze"],capacity:240,remainingCapacity:0,entryFeeMinor:1800 },
  { id:"race-atlas-500",eventId:"event-atlas-sprints",name:"500 m Sprint",formatId:"distance-500",distanceMeters:500,divisions:["men","women"],ageCategoryIds:["u23","senior-23-39","masters-40-44"],weightCategoryIds:["open-weight"],adaptiveClassificationIds:[],machineProviderIds:["concept2","rp3"],machineClassIds:["event-approved"],verificationRequirement:"organizer-verified",scoring:"elapsed_time_ascending",medals:["Gold","Silver","Bronze"],capacity:80,remainingCapacity:22,entryFeeMinor:1500 },
  { id:"race-university-relay",eventId:"event-north-relay",name:"2,000 m University Relay",formatId:"relay-2000",distanceMeters:2000,divisions:["men","women"],ageCategoryIds:["u23"],weightCategoryIds:["open-weight"],adaptiveClassificationIds:[],machineProviderIds:["concept2"],machineClassIds:["static-air-resistance"],verificationRequirement:"organizer-verified",scoring:"team_aggregate",medals:["Campus Cup"],capacity:32,remainingCapacity:9,entryFeeMinor:4000 },
  { id:"race-national-2k",eventId:"event-national-demo",name:"National 2,000 m Championship",formatId:"distance-2000",distanceMeters:2000,divisions:["men","women","lightweight-men","lightweight-women","adaptive-para"],ageCategoryIds:["u19","u23","senior-23-39","masters-40-44","masters-45-49"],weightCategoryIds:["open-weight","lightweight"],adaptiveClassificationIds:["iar1","iar2"],machineProviderIds:["concept2"],machineClassIds:["static-air-resistance"],verificationRequirement:"federation-certified",rankingDefinitionId:"ranking-national-demo-2k",scoring:"elapsed_time_ascending",medals:["National Champion","Silver","Bronze"],capacity:400,remainingCapacity:116,entryFeeMinor:3500 },
  { id:"race-virtual-30",eventId:"event-rowform-virtual-league",name:"30-minute Distance",formatId:"time-1800",durationSeconds:1800,divisions:["men","women","adaptive-para"],ageCategoryIds:["u23","senior-23-39","masters-40-44","masters-45-49"],weightCategoryIds:["open-weight"],adaptiveClassificationIds:["iar2"],machineProviderIds:["concept2","rp3","waterrower","technogym","matrix"],machineClassIds:["event-approved"],verificationRequirement:"photo-confirmed",rankingDefinitionId:"ranking-virtual-league-30",scoring:"distance_descending",medals:["League finisher"],capacity:1000,remainingCapacity:742,entryFeeMinor:1200 },
  { id:"race-continental-1k",eventId:"event-continental-demo",name:"Continental 1,000 m",formatId:"distance-1000",distanceMeters:1000,divisions:["men","women","lightweight-men","lightweight-women","adaptive-para"],ageCategoryIds:["u19","u23","senior-23-39"],weightCategoryIds:["open-weight","lightweight"],adaptiveClassificationIds:["iar1","iar2"],machineProviderIds:["concept2"],machineClassIds:["static-air-resistance"],verificationRequirement:"federation-certified",scoring:"elapsed_time_ascending",medals:["Continental podium"],entryFeeMinor:2800 },
  { id:"race-global-500",eventId:"event-global-demo",name:"International 500 m",formatId:"distance-500",distanceMeters:500,divisions:["men","women"],ageCategoryIds:["u23","senior-23-39"],weightCategoryIds:["open-weight"],adaptiveClassificationIds:[],machineProviderIds:["concept2"],machineClassIds:["static-air-resistance"],verificationRequirement:"federation-certified",scoring:"elapsed_time_ascending",medals:["International podium"],capacity:300,remainingCapacity:0,entryFeeMinor:0 },
  { id:"race-charity-5k",eventId:"event-river-charity",name:"5,000 m Community Row",formatId:"distance-5000",distanceMeters:5000,divisions:["men","women","adaptive-para"],ageCategoryIds:["u23","senior-23-39","masters-40-44"],weightCategoryIds:["open-weight"],adaptiveClassificationIds:["iar2"],machineProviderIds:["concept2","rp3","waterrower","technogym","matrix","other"],machineClassIds:["event-approved"],verificationRequirement:"manual",scoring:"elapsed_time_ascending",medals:["Charity participant"],capacity:500,remainingCapacity:381,entryFeeMinor:500 },
];

export const PROMOTIONS: EventPromotion[] = [
  { id:"promo-virtual-feature",type:"featured_event",startsAt:"2026-07-01",endsAt:"2026-09-30",targetRegion:"Global",targetAthleteSegment:"All indoor rowers",commercialCampaignId:"campaign-prototype-001",disclosureLabel:"Featured" },
  { id:"promo-national",type:"promoted_search",startsAt:"2026-07-10",endsAt:"2026-08-31",targetRegion:"North Africa",targetAthleteSegment:"Competition athletes",commercialCampaignId:"campaign-prototype-002",disclosureLabel:"Promoted" },
  { id:"promo-charity",type:"sponsored_event",startsAt:"2026-07-15",endsAt:"2026-10-15",targetRegion:"Global",targetAthleteSegment:"Community athletes",commercialCampaignId:"campaign-prototype-003",disclosureLabel:"Sponsored" },
];

export const FEE_CONFIGURATIONS: FeeConfiguration[] = [
  { id:"fee-virtual",eventId:"event-rowform-virtual-league",mode:"athlete_paid",percentageBasisPoints:500,fixedFeeMinor:100,organizerSubsidyMinor:0,promotionalDiscountMinor:0,couponCode:"ROWFORM10",taxRateBasisPoints:0 },
  { id:"fee-atlas",eventId:"event-atlas-sprints",mode:"hybrid",percentageBasisPoints:300,fixedFeeMinor:50,organizerSubsidyMinor:75,promotionalDiscountMinor:0,taxRateBasisPoints:0 },
  { id:"fee-charity",eventId:"event-river-charity",mode:"waived",percentageBasisPoints:0,fixedFeeMinor:0,organizerSubsidyMinor:0,promotionalDiscountMinor:0,taxRateBasisPoints:0 },
];

const common={operationalStatus:"active" as const,registrationOpensAt:"2026-06-01T09:00:00Z",currency:"EUR",refundPolicy:"Refunds are not processed in this prototype. Final policy is controlled by the organizer and shown before live checkout.",transferPolicy:"Registration transfers are not available in the prototype.",logoText:"RF",noticeIds:[] as string[],waiverIds:[] as string[]};
export const EVENTS: EventDefinition[] = [
  { ...common,id:"event-rowform-virtual-league",slug:"rowform-global-virtual-league",title:"Rowform Global Virtual League",summary:"A four-round, machine-inclusive virtual league built as a Rowform registration prototype.",description:"Compete from home, a gym, university, or club. Results remain separated by machine class and verification tier; no hidden cross-machine equivalence is applied.",organizerId:"org-rowform-events",type:"virtual",level:"international",format:"virtual",lifecycle:"registration_open",registrationStatus:"open",commerceMode:"rowform_registration",countryCode:"XX",country:"Worldwide",continent:"Global",city:"Online",venue:"Virtual competition",timezone:"UTC",startsAt:"2026-09-12T08:00:00Z",endsAt:"2026-09-20T20:00:00Z",registrationClosesAt:"2026-09-10T20:00:00Z",contactEmail:"events@rowform.test",eligibilitySummary:"Independent and club athletes aged 19+; adaptive category available for the configured race.",machineRuleSummary:"Multiple providers accepted; rankings are separated by approved machine class.",verificationAuthority:"Rowform Events Lab prototype review team",verificationLevel:"photo-confirmed",raceIds:["race-virtual-30"],promotionIds:["promo-virtual-feature"],sourceIds:["source-rowform-virtual"],waiverIds:["waiver-rowform-virtual"],website:"https://example.com/rowform-events" },
  { ...common,id:"event-atlas-sprints",slug:"atlas-club-sprint-regatta",title:"Atlas Club Sprint Regatta",summary:"A compact local sprint programme with transparent prototype registration fees.",description:"A fictional local club Event created to demonstrate organizer-owned Rowform registration, limited capacity, eligibility, and Event verification without implying federation status.",organizerId:"org-atlas-club",type:"club",level:"club",format:"physical",lifecycle:"registration_open",registrationStatus:"open",commerceMode:"rowform_registration",countryCode:"DZ",country:"Algeria",continent:"Africa",city:"Algiers",venue:"Atlas Training Hall (prototype venue)",timezone:"Africa/Algiers",startsAt:"2026-08-29T08:00:00Z",endsAt:"2026-08-29T16:00:00Z",registrationClosesAt:"2026-08-24T22:00:00Z",contactEmail:"events@atlas-rowing.example",eligibilitySummary:"Open to independent and club athletes in the configured age and division classes.",machineRuleSummary:"Event-approved Concept2 and RP3 classes; results remain class-specific.",verificationAuthority:"Atlas Rowing Club prototype officials",verificationLevel:"organizer-verified",raceIds:["race-atlas-500"],promotionIds:[],sourceIds:["source-atlas"],waiverIds:["waiver-atlas"] },
  { ...common,id:"event-north-relay",slug:"north-harbour-university-relay",title:"North Harbour University Relay",summary:"University teams race a structured 2,000 m relay.",description:"A fictional university Event demonstrating institution eligibility, team capacity, and external registration handoff.",organizerId:"org-north-university",type:"university",level:"university",format:"physical",lifecycle:"registration_open",registrationStatus:"open",commerceMode:"external_registration",countryCode:"GB",country:"United Kingdom",continent:"Europe",city:"Newcastle",venue:"North Harbour Sports Centre (prototype)",timezone:"Europe/London",startsAt:"2026-10-03T09:00:00Z",endsAt:"2026-10-03T18:00:00Z",registrationClosesAt:"2026-09-20T22:59:00Z",currency:"GBP",contactEmail:"sport@northharbour.example",eligibilitySummary:"University teams; organizer confirms student eligibility externally.",machineRuleSummary:"Concept2 static air-resistance class under a common event setup.",verificationAuthority:"University competition officials",verificationLevel:"organizer-verified",raceIds:["race-university-relay"],promotionIds:[],sourceIds:["source-university"],waiverIds:[],externalRegistrationUrl:"https://example.com/university-relay-register" },
  { ...common,id:"event-national-demo",slug:"national-indoor-championship-demo",title:"National Indoor Championship Demo",summary:"A fictional federation-style championship listing for architecture testing.",description:"This is prototype content, not a real championship or federation partnership. It demonstrates national eligibility, strong verification, external registration, and transparent source attribution.",organizerId:"org-national-demo",type:"national-championship",level:"national",format:"hybrid",lifecycle:"registration_open",registrationStatus:"open",commerceMode:"external_registration",countryCode:"DZ",country:"Algeria",continent:"Africa",city:"Oran",venue:"National Arena (prototype venue)",timezone:"Africa/Algiers",startsAt:"2026-11-14T08:00:00Z",endsAt:"2026-11-15T18:00:00Z",registrationClosesAt:"2026-10-31T22:00:00Z",contactEmail:"indoor@national-demo.example",eligibilitySummary:"Federation-defined categories; this prototype does not perform eligibility decisions.",machineRuleSummary:"Named static air-resistance equipment under a federation-style protocol.",verificationAuthority:"Fictional demonstration federation",verificationLevel:"federation-certified",raceIds:["race-national-2k"],promotionIds:["promo-national"],sourceIds:["source-national"],waiverIds:[],externalRegistrationUrl:"https://example.com/national-demo-register" },
  { ...common,id:"event-continental-demo",slug:"continental-indoor-cup-demo",title:"Continental Indoor Cup Demo",summary:"A prototype continental-level Event with information-only status.",description:"A fictional listing reserved to demonstrate continental event taxonomy. No registration, payment, endorsement, or official affiliation is claimed.",organizerId:"org-continental-demo",type:"continental-championship",level:"continental",format:"hybrid",lifecycle:"published",registrationStatus:"not_open",commerceMode:"information_only",countryCode:"FR",country:"France",continent:"Europe",city:"Lyon",venue:"Competition venue to be confirmed",timezone:"Europe/Paris",startsAt:"2027-02-06T08:00:00Z",endsAt:"2027-02-07T18:00:00Z",registrationClosesAt:"2027-01-20T22:00:00Z",contactEmail:"events@continental-demo.example",eligibilitySummary:"Categories and qualification are pending organizer publication.",machineRuleSummary:"Machine protocol is not yet published.",verificationAuthority:"Authority not yet confirmed",verificationLevel:"manual",raceIds:["race-continental-1k"],promotionIds:[],sourceIds:["source-continental"],waiverIds:[] },
  { ...common,id:"event-global-demo",slug:"global-indoor-championship-preview",title:"Global Indoor Championship Preview",summary:"Invitation-only prototype showing an international championship information model.",description:"Fictional demonstration content. Rowform is not claiming World Rowing, federation, or organizer affiliation, and no official marks are used.",organizerId:"org-global-demo",type:"world-championship",level:"international",format:"physical",lifecycle:"published",registrationStatus:"not_open",commerceMode:"invite_only",countryCode:"NL",country:"Netherlands",continent:"Europe",city:"Amsterdam",venue:"International Hall (prototype venue)",timezone:"Europe/Amsterdam",startsAt:"2027-03-20T08:00:00Z",endsAt:"2027-03-21T18:00:00Z",registrationClosesAt:"2027-02-28T22:00:00Z",contactEmail:"competition@global-demo.example",eligibilitySummary:"Invitation and qualification required; demonstration rules only.",machineRuleSummary:"Single named competition class; final protocol pending.",verificationAuthority:"Prototype international organizer",verificationLevel:"federation-certified",raceIds:["race-global-500"],promotionIds:[],sourceIds:["source-global"],waiverIds:[] },
  { ...common,id:"event-river-charity",slug:"river-restoration-charity-row",title:"River Restoration Charity Row",summary:"A sponsored community 5K with visible promotional disclosure.",description:"A fictional charitable Event showing broad machine participation and a visibly sponsored placement. No donation or environmental impact claim is made by logged distance.",organizerId:"org-rowform-events",type:"charity",level:"community",format:"virtual",lifecycle:"registration_open",registrationStatus:"open",commerceMode:"rowform_registration",countryCode:"XX",country:"Worldwide",continent:"Global",city:"Online",venue:"Virtual competition",timezone:"UTC",startsAt:"2026-10-10T00:00:00Z",endsAt:"2026-10-18T23:59:00Z",registrationClosesAt:"2026-10-08T23:59:00Z",contactEmail:"events@rowform.test",eligibilitySummary:"Open participation with adaptive classification support.",machineRuleSummary:"All declared machines accepted for participation; no cross-machine strict ranking.",verificationAuthority:"Rowform prototype review",verificationLevel:"manual",raceIds:["race-charity-5k"],promotionIds:["promo-charity"],sourceIds:["source-charity"],waiverIds:["waiver-charity"] },
  { ...common,id:"event-mvo-2026",slug:"mediterranean-virtual-open-2026",title:"Mediterranean Virtual Open",summary:"Completed prototype Event with one canonical verified result across Rowform surfaces.",description:"A fictional completed virtual Event used to demonstrate result provenance, ranking eligibility, and Athlete Passport history consistently.",organizerId:"org-rowform-events",type:"virtual",level:"international",format:"virtual",lifecycle:"results_verified",registrationStatus:"completed",commerceMode:"information_only",countryCode:"XX",country:"Mediterranean region",continent:"Europe",city:"Online",venue:"Virtual competition",timezone:"UTC",startsAt:"2026-06-18T00:00:00Z",endsAt:"2026-06-20T23:59:00Z",registrationClosesAt:"2026-06-15T23:59:00Z",contactEmail:"events@rowform.test",eligibilitySummary:"Configured senior and masters divisions under prototype event rules.",machineRuleSummary:"Concept2 static air-resistance class for this result board.",verificationAuthority:"Rowform Events Lab prototype officials",verificationLevel:"organizer-verified",raceIds:["race-mvo-2k"],promotionIds:[],sourceIds:["source-mvo"],waiverIds:[] },
];

export const EVENT_SOURCES: EventSource[] = EVENTS.map((event)=>({ id:`source-${event.id.replace("event-","")}`,eventId:event.id,label:event.organizerId==="org-rowform-events"?"Rowform prototype catalogue":"Organizer-supplied prototype listing",ownerName:ORGANIZERS.find((item)=>item.id===event.organizerId)?.name??"Prototype source",reviewedAt:"2026-07-22" }));
export const EVENT_NOTICES: EventNotice[] = [{ id:"notice-mvo-results",eventId:"event-mvo-2026",publishedAt:"2026-06-22T12:00:00Z",title:"Results verified",body:"The prototype result set completed organizer review.",severity:"information" }];
export const WAIVERS: Waiver[] = [
  { id:"waiver-rowform-virtual",eventId:"event-rowform-virtual-league",version:"1.0-prototype",title:"Event participation waiver",summary:"Prototype acknowledgement only; no legal registration or payment is completed.",required:true },
  { id:"waiver-atlas",eventId:"event-atlas-sprints",version:"1.0-prototype",title:"Club Event waiver",summary:"Prototype acknowledgement for the demonstration registration flow.",required:true },
  { id:"waiver-charity",eventId:"event-river-charity",version:"1.0-prototype",title:"Community Event acknowledgement",summary:"Prototype acknowledgement; no donation or payment is processed.",required:true },
];

export const CANONICAL_REGISTRATION: Registration = { id:"registration-mvo-md-001",reference:"RF-EVT-MVO-2026-018",athleteId:CURRENT_ATHLETE.id,passportId:CURRENT_ATHLETE.passportId,eventId:"event-mvo-2026",raceId:"race-mvo-2k",paymentId:"payment-mvo-md-001",resultId:"result-mvo-md-001",divisionId:"men",ageCategoryId:"senior-23-39",weightCategoryId:"open-weight",affiliation:"independent",registrationStatus:"confirmed",paymentStatus:"paid",acceptedWaiverIds:[],createdAt:"2026-05-28T14:20:00Z" };
export const CANONICAL_PAYMENT: PaymentRecord = { id:"payment-mvo-md-001",registrationId:CANONICAL_REGISTRATION.id,providerId:"historical-prototype",currency:"EUR",subtotalMinor:1800,rowformServiceFeeMinor:150,organizerPayoutMinor:1800,taxMinor:0,refundMinor:0,status:"paid",payoutStatus:"not_applicable",chargebackStatus:"none",createdAt:"2026-05-28T14:20:00Z",paidAt:"2026-05-28T14:21:00Z" };
export const EVENT_RESULTS: EventResult[] = [{ id:"result-mvo-md-001",eventId:"event-mvo-2026",raceId:"race-mvo-2k",registrationId:CANONICAL_REGISTRATION.id,athleteId:CURRENT_ATHLETE.id,athleteName:CURRENT_ATHLETE.name,resultValue:438700,displayResult:"7:18.7",status:"official",verificationAuthority:"Rowform Events Lab prototype officials",verificationTier:"organizer-verified",rankingDefinitionId:"ranking-mvo-2026-2k",rankingRecordId:"rank-mvo-2026-md",passportCompetitionRecordId:"c1",passportTimelineEntryId:"t4",placing:"18th of 146 · Top 13%" }];

export function eventBySlug(slug:string){return EVENTS.find((event)=>event.slug===slug)}
export function eventOrganizer(event:EventDefinition){return ORGANIZERS.find((organizer)=>organizer.id===event.organizerId)!}
export function eventRaces(event:EventDefinition){return event.raceIds.map((id)=>RACES.find((race)=>race.id===id)).filter((race):race is Race=>Boolean(race))}
export function eventPromotions(event:EventDefinition){return event.promotionIds.map((id)=>PROMOTIONS.find((promotion)=>promotion.id===id)).filter((promotion):promotion is EventPromotion=>Boolean(promotion))}
export function feeConfiguration(eventId:string){return FEE_CONFIGURATIONS.find((fee)=>fee.eventId===eventId)??{id:`waived-${eventId}`,eventId,mode:"waived",percentageBasisPoints:0,fixedFeeMinor:0,organizerSubsidyMinor:0,promotionalDiscountMinor:0,taxRateBasisPoints:0} as FeeConfiguration}
export function calculateFees(subtotalMinor:number,fee:FeeConfiguration,coupon?:string):FeeBreakdown { const raw=Math.round(subtotalMinor*fee.percentageBasisPoints/10000)+fee.fixedFeeMinor; const athleteFee=fee.mode==="organizer_funded"||fee.mode==="waived"?0:Math.max(0,raw-fee.organizerSubsidyMinor); const organizerFee=fee.mode==="organizer_funded"?raw:fee.mode==="hybrid"?fee.organizerSubsidyMinor:0; const couponDiscount=coupon&&fee.couponCode&&coupon.toUpperCase()===fee.couponCode?Math.round(subtotalMinor*.1):0; const discount=Math.min(subtotalMinor,fee.promotionalDiscountMinor+couponDiscount); const taxable=Math.max(0,subtotalMinor-discount+athleteFee); const tax=Math.round(taxable*fee.taxRateBasisPoints/10000); return {subtotalMinor,serviceFeeMinor:athleteFee,taxMinor:tax,discountMinor:discount,organizerSubsidyMinor:fee.organizerSubsidyMinor,totalMinor:taxable+tax,organizerPayoutMinor:Math.max(0,subtotalMinor-discount-organizerFee)} }
export function money(minor:number,currency:string){return new Intl.NumberFormat("en",{style:"currency",currency}).format(minor/100)}
export function commerceCta(event:EventDefinition){if(event.operationalStatus==="cancelled")return "Event cancelled";if(event.operationalStatus==="registration_suspended")return "Registration suspended";if(event.commerceMode==="external_registration")return "Register on organizer website";if(event.commerceMode==="rowform_registration"&&event.registrationStatus==="open")return "Register with Rowform";if(event.commerceMode==="invite_only")return "Invitation required";if(event.registrationStatus==="not_open")return "Registration not yet open";if(event.registrationStatus==="completed")return "View verified results";return "View event information"}
