import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, CalendarDays, Clock3, ExternalLink, MapPin, ShieldCheck, UsersRound } from "lucide-react";
import { EventResultsBoard } from "@/components/events/event-results-board";
import { AGE_CATEGORIES, COMPETITION_DIVISIONS, labelFor, VERIFICATION_OPTIONS, WEIGHT_CATEGORIES } from "@/lib/competition-taxonomy";
import { commerceCta, EVENT_NOTICES, EVENT_RESULTS, EVENT_SOURCES, EVENTS, eventBySlug, eventOrganizer, eventPromotions, eventRaces, money } from "@/lib/events/data";
import { getMachineProvider } from "@/lib/machine-data";

export function generateStaticParams(){return EVENTS.map((event)=>({slug:event.slug}))}
const fullDate=(value:string,timeZone:string)=>new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short",timeZone}).format(new Date(value));

export default async function EventDetailPage({params}:{params:Promise<{slug:string}>}){
  const event=eventBySlug((await params).slug);if(!event)notFound();
  const organizer=eventOrganizer(event);const races=eventRaces(event);const promotion=eventPromotions(event)[0];
  const results=EVENT_RESULTS.filter((result)=>result.eventId===event.id);const source=EVENT_SOURCES.find((item)=>item.eventId===event.id);const notices=EVENT_NOTICES.filter((notice)=>notice.eventId===event.id);
  const external=event.commerceMode==="external_registration";const cta=commerceCta(event);const disabled=["information_only","invite_only"].includes(event.commerceMode);
  const actionHref=external?event.externalRegistrationUrl:event.commerceMode==="rowform_registration"?`/events/${event.slug}/register`:`/events/${event.slug}#event-information`;
  const action=<Link href={actionHref??"#event-information"} target={external?"_blank":undefined} rel={external?"noreferrer":undefined} aria-disabled={disabled} className={`inline-flex min-h-12 items-center gap-2 rounded-full px-6 text-sm font-black ${disabled?"pointer-events-none bg-white/15 text-white/65":"bg-[#ff6b35] text-white"}`}>{cta}{external?<ExternalLink size={16}/>:<ArrowRight size={16}/>}</Link>;
  return <div>
    <Link href="/events" className="inline-flex min-h-11 items-center gap-2 text-sm font-black text-[#36534a]"><ArrowLeft size={17}/> Event marketplace</Link>
    <header className="relative mt-4 overflow-hidden rounded-[2rem] bg-[#0d2b24] p-6 text-white sm:p-10"><div className="surface-grid absolute inset-0 opacity-30"/><div className="relative max-w-4xl"><div className="flex flex-wrap gap-2">{promotion&&<span className="rounded-full bg-[#ff6b35] px-3 py-1 text-[10px] font-black uppercase tracking-[.14em]">{promotion.disclosureLabel}</span>}<span className="rounded-full border border-white/20 px-3 py-1 text-[10px] font-black uppercase tracking-[.14em]">{event.lifecycle.replaceAll("_"," ")}</span><span className="rounded-full border border-white/20 px-3 py-1 text-[10px] font-black uppercase tracking-[.14em]">{event.format}</span></div><h1 className="display-type mt-5 text-5xl font-black leading-none sm:text-7xl">{event.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/75">{event.description}</p><div className="mt-7 flex flex-wrap gap-3">{action}</div>{external&&<p className="mt-3 text-xs text-white/60">Registration and payment are handled by the organizer, not Rowform.</p>}</div></header>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_22rem]"><main className="min-w-0 space-y-6">
      <section id="event-information" className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.14em] text-[#d94d1c]">Event information</p><h2 className="mt-2 text-2xl font-black">Start line essentials</h2><dl className="mt-6 grid gap-5 sm:grid-cols-2"><Info icon={<UsersRound/>} label="Organizer" value={organizer.name} detail={organizer.verificationStatus.replaceAll("_"," ")}/><Info icon={<MapPin/>} label="Venue" value={event.venue} detail={`${event.city}, ${event.country}`}/><Info icon={<CalendarDays/>} label="Competition" value={fullDate(event.startsAt,event.timezone)} detail={`Ends ${fullDate(event.endsAt,event.timezone)}`}/><Info icon={<Clock3/>} label="Registration deadline" value={fullDate(event.registrationClosesAt,event.timezone)} detail={event.timezone}/></dl></section>
      <section className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.14em] text-[#d94d1c]">Race programme</p><h2 className="mt-2 text-2xl font-black">Choose your test</h2><div className="mt-5 space-y-4">{races.map((race)=><article key={race.id} className="rounded-2xl bg-[#f5f7f4] p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black">{race.name}</h3><p className="mt-1 text-xs text-[#718078]">{race.scoring.replaceAll("_"," ")} · {labelFor(VERIFICATION_OPTIONS,race.verificationRequirement)}</p></div><p className="text-xl font-black">{money(race.entryFeeMinor,event.currency)}</p></div><div className="mt-4 flex flex-wrap gap-2">{race.divisions.map((id)=><span key={id} className="rounded-full bg-white px-3 py-1 text-xs font-bold">{labelFor(COMPETITION_DIVISIONS,id)}</span>)}{race.ageCategoryIds.slice(0,3).map((id)=><span key={id} className="rounded-full bg-white px-3 py-1 text-xs font-bold">{labelFor(AGE_CATEGORIES,id)}</span>)}</div><p className="mt-3 text-xs leading-5 text-[#62706b]">Machines: {race.machineProviderIds.map((id)=>getMachineProvider(id)?.displayName??id).join(", ")}. {race.remainingCapacity!==undefined?`${race.remainingCapacity} of ${race.capacity} places remain.`:"Capacity not published."}</p></article>)}</div></section>
      <section className="grid gap-5 md:grid-cols-2"><article className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Eligibility & categories</h2><p className="mt-3 text-sm leading-6 text-[#62706b]">{event.eligibilitySummary}</p><h3 className="mt-5 text-xs font-black uppercase text-[#718078]">Weight categories</h3><p className="mt-2 text-sm font-bold">{[...new Set(races.flatMap((race)=>race.weightCategoryIds))].map((id)=>labelFor(WEIGHT_CATEGORIES,id)).join(", ")}</p><h3 className="mt-5 text-xs font-black uppercase text-[#718078]">Adaptive classifications</h3><p className="mt-2 text-sm font-bold">{races.some((race)=>race.adaptiveClassificationIds.length)?races.flatMap((race)=>race.adaptiveClassificationIds).join(", ").toUpperCase():"Not configured for this programme"}</p></article><article className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-6"><h2 className="text-xl font-black">Machine & verification rules</h2><p className="mt-3 text-sm leading-6 text-[#62706b]">{event.machineRuleSummary}</p><p className="mt-4 flex items-start gap-2 rounded-2xl bg-[#eef8f4] p-4 text-sm"><ShieldCheck className="mt-0.5 shrink-0 text-[#16725e]" size={18}/><span><strong className="block">{event.verificationAuthority}</strong><span className="mt-1 block text-xs text-[#62706b]">Minimum: {labelFor(VERIFICATION_OPTIONS,event.verificationLevel)}</span></span></p></article></section>
      <section className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7"><h2 className="text-2xl font-black">Policies, contact & notices</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Policy title="Refund summary" body={event.refundPolicy}/><Policy title="Transfer summary" body={event.transferPolicy}/><div><h3 className="text-xs font-black uppercase text-[#718078]">Contact</h3><a href={`mailto:${event.contactEmail}`} className="mt-2 block text-sm font-black text-[#16725e] underline">{event.contactEmail}</a></div><div><h3 className="text-xs font-black uppercase text-[#718078]">Source attribution</h3><p className="mt-2 text-sm font-bold">{source?.label??"Prototype catalogue"}</p><p className="mt-1 text-xs text-[#718078]">Owner: {source?.ownerName??organizer.name}</p></div></div>{notices.map((notice)=><aside key={notice.id} className="mt-5 rounded-2xl bg-[#fff7f2] p-4"><p className="font-black">{notice.title}</p><p className="mt-1 text-sm text-[#6d4a3a]">{notice.body}</p></aside>)}</section>
      {results.length > 0 && <EventResultsBoard results={results} races={races} />}
    </main><aside className="h-fit rounded-3xl border border-[#dfe5e1] bg-white p-5 xl:sticky xl:top-24"><p className="text-xs font-black uppercase tracking-[.14em] text-[#d94d1c]">Registration</p><p className="mt-3 text-3xl font-black">{races.some((race)=>race.entryFeeMinor)?`From ${money(Math.min(...races.map((race)=>race.entryFeeMinor)),event.currency)}`:"No entry fee"}</p><p className="mt-2 text-xs leading-5 text-[#718078]">Any Rowform service fee, taxes, and discount are shown before prototype confirmation. Live payments are not configured.</p><div className="mt-5 rounded-2xl bg-[#f5f7f4] p-4 text-xs leading-5"><p className="font-black">Commerce mode</p><p className="mt-1 text-[#62706b]">{event.commerceMode.replaceAll("_"," ")}</p></div><div className="mt-5">{action}</div></aside></div>
  </div>
}

function Info({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className="flex gap-3"><span className="text-[#16725e]">{icon}</span><div><dt className="text-xs text-[#718078]">{label}</dt><dd className="mt-1 font-black">{value}</dd><p className="mt-1 text-xs text-[#718078]">{detail}</p></div></div>}
function Policy({title,body}:{title:string;body:string}){return <div><h3 className="text-xs font-black uppercase text-[#718078]">{title}</h3><p className="mt-2 text-sm leading-6">{body}</p></div>}
