import { AtSign, LockKeyhole, ShieldCheck } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { hasSupabaseConfig } from "@/lib/supabase/config";
import { changeEmail, signOut } from "@/app/(auth)/auth-actions";

const inputClass = "mt-1.5 min-h-11 w-full rounded-xl border border-[#ccd6d1] bg-white px-3 text-sm font-bold outline-none focus:border-[#16725e] focus:ring-2 focus:ring-[#16725e]/20";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ error?: string; message?: string }> }) {
  const query = await searchParams; const user = hasSupabaseConfig() ? (await (await createClient()).auth.getUser()).data.user : null;
  return <div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.16em] text-[#d94d1c]">Private account controls</p><h1 className="display-type mt-3 text-4xl font-black">Account settings</h1><p className="mt-3 text-sm leading-6 text-[#62706b]">Authentication identity, public Passport fields, and communication permissions are intentionally separate.</p>{query.error && <p role="alert" className="mt-5 rounded-xl bg-[#fff1eb] p-3 text-sm font-bold text-[#a43f20]">{query.error}</p>}{query.message && <p role="status" className="mt-5 rounded-xl bg-[#eaf6f1] p-3 text-sm font-bold text-[#176a55]">{query.message}</p>}<div className="mt-6 grid gap-5"><section className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7"><div className="flex gap-3"><AtSign className="text-[#16725e]" /><div><h2 className="text-xl font-black">Authentication email</h2><p className="mt-1 text-sm text-[#62706b]">Private account credential. Never displayed in your public Passport.</p></div></div><dl className="mt-5 rounded-2xl bg-[#f5f7f4] p-4 text-sm"><dt className="text-xs text-[#718078]">Current email</dt><dd className="mt-1 font-black">{user?.email ?? "Supabase not configured"}</dd><dt className="mt-3 text-xs text-[#718078]">Status</dt><dd className="mt-1 font-black">{user?.email_confirmed_at ? "Verified" : "Not yet verified"}</dd></dl><form action={changeEmail} className="mt-5"><label className="text-xs font-bold text-[#475b54]">New email<input name="email" type="email" autoComplete="email" required className={inputClass} /></label><button className="mt-3 min-h-11 rounded-full bg-[#0d2b24] px-5 text-sm font-black text-white">Request secure email change</button></form></section><section className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7"><div className="flex gap-3"><ShieldCheck className="text-[#16725e]" /><div><h2 className="text-xl font-black">Privacy boundary</h2><p className="mt-1 text-sm leading-6 text-[#62706b]">Passport visibility never grants access to your email, exact birth date, provider identities, or consent history.</p></div></div></section><section className="rounded-3xl border border-[#dfe5e1] bg-white p-5 sm:p-7"><div className="flex items-center justify-between gap-4"><div className="flex gap-3"><LockKeyhole className="text-[#d94d1c]" /><div><h2 className="font-black">End this session</h2><p className="mt-1 text-sm text-[#62706b]">Sign out on this device.</p></div></div><form action={signOut}><button className="min-h-11 rounded-full border border-[#d3dcd8] px-5 text-sm font-black">Sign out</button></form></div></section></div></div>;
}
