export type Json=string|number|boolean|null|{[key:string]:Json|undefined}|Json[];
type Relationship={foreignKeyName:string;columns:string[];isOneToOne?:boolean;referencedRelation:string;referencedColumns:string[]};
type Table<Row,Insert=Partial<Row>,Update=Partial<Insert>>={Row:Row;Insert:Insert;Update:Update;Relationships:Relationship[]};
export type ProfileRow={id:string;auth_user_id:string;email:string|null;email_verified_at:string|null;first_name:string|null;last_name:string|null;display_name:string|null;date_of_birth:string|null;gender:string|null;country_code:string|null;city_id:string|null;city_name:string|null;city_region:string|null;city_latitude:number|null;city_longitude:number|null;city_is_manual:boolean;manual_city:string|null;timezone:string;preferred_units:Json;training_context:string|null;primary_club_id:string|null;preferred_machine_model_id:string|null;preferred_machine_label:string|null;passport_id:string;biography:string|null;visibility:"private"|"connections"|"public"|"event_organizers";onboarding_status:"not_started"|"in_progress"|"completed"|"skipped_optional";onboarding_completed_at:string|null;created_at:string;updated_at:string;deleted_at:string|null};
export type PassportRow={id:string;profile_id:string;public_slug:string;bio:string|null;avatar_url:string|null;primary_machine_provider_id:string|null;primary_machine_model_id:string|null;passport_status:string;verification_status:string;visibility:"private"|"connections"|"public"|"event_organizers";created_at:string;updated_at:string};
export type VisibilityRow={profile_id:string;full_name:boolean;location:boolean;club:boolean;age_category:boolean;workouts:boolean;rankings:boolean;achievements:boolean;expeditions:boolean;updated_at:string};
export type WorkoutRow={id:string;user_id:string;title:string|null;notes:string|null;workout_type:string;workout_role:string;started_at:string;ended_at:string|null;timezone:string|null;duration_ms:number|null;distance_meters:number|null;average_spm:number|null;average_heart_rate_bpm:number|null;average_power_watts:number|null;average_pace_ms_per_500m:number|null;calories_kcal:number|null;machine_provider_key:string|null;machine_model_key:string|null;machine_class:string|null;source_method:string;verification_tier:string|null;visibility:"private"|"connections"|"public";ranking_eligible:boolean;metadata:Json;created_at:string;updated_at:string;deleted_at:string|null};

export type Database={public:{Tables:{
 profiles:Table<ProfileRow,Partial<ProfileRow>&{id:string;auth_user_id?:string}>;
 athlete_passports:Table<PassportRow,Partial<PassportRow>&{profile_id:string;public_slug:string}>;
 profile_visibility_settings:Table<VisibilityRow,Partial<VisibilityRow>&{profile_id:string}>;
 workouts:Table<WorkoutRow,Partial<WorkoutRow>&{user_id:string;started_at:string}>;
 communication_consents:Table<{id:string;athlete_id:string;purpose:string;channel:string;granted:boolean;disclosure_version:string;recorded_at:string;withdrawn_at:string|null},Record<string,unknown>>;
 club_memberships:Table<Record<string,unknown>,Record<string,unknown>>;
 club_submissions:Table<Record<string,unknown>,Record<string,unknown>>;
 clubs:Table<{id:string;official_name:string;country_code:string;city_name:string;club_type:string;website:string|null;federation_affiliation:string|null;verification_status:string;active:boolean;source_label:string},Record<string,unknown>>;
 machine_models:Table<{id:string;key:string|null;provider_key:string|null;manufacturer:string;model_name:string;suggested_machine_class:string|null;active:boolean},Record<string,unknown>>;
};Views:{public_athlete_passports:{Row:{public_slug:string;display_name:string|null;country_code:string|null;city:string|null;club_name:string|null;bio:string|null;avatar_url:string|null;verification_status:string};Relationships:[]};public_ranking_results:{Row:Record<string,unknown>;Relationships:[]};public_club_summaries:{Row:Record<string,unknown>;Relationships:[]}};Functions:Record<string,never>;Enums:{onboarding_status:ProfileRow["onboarding_status"];passport_visibility:PassportRow["visibility"];record_visibility:WorkoutRow["visibility"]};CompositeTypes:Record<string,never>}};
