"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import { Filter,Plus,RotateCcw,ShieldCheck } from "lucide-react";
import { labelFor,MACHINE_CLASSES,VERIFICATION_OPTIONS,type MachineClassId,type VerificationId } from "@/lib/competition-taxonomy";
import { CONNECTION_METHODS,getMachineModel,getMachineProvider,MACHINE_MODELS,MACHINE_PROVIDERS,modelsForProvider,OTHER_MODEL_ID,UNKNOWN_MODEL_ID,type MachineProviderId } from "@/lib/machine-data";
import { workouts as initialWorkouts } from "@/lib/mock-data";

type WorkoutRow={id:number;detailId?:string;title:string;providerId:MachineProviderId;modelId:string;otherModel?:string;machineClassId:Exclude<MachineClassId,"all-comparable">;connectionMethod:string;verificationId:Exclude<VerificationId,"all-accepted">;sessionType:string;distance:string;time:string;pace:string;date:string};
const sessionTypes=[{id:"all",label:"All sessions"},{id:"training",label:"Training session"},{id:"ranking-eligible",label:"Ranking-eligible result"},{id:"event-result",label:"Event result"},{id:"personal-best",label:"Personal best"}] as const;
const selectClass="mt-1.5 min-h-11 w-full rounded-xl border border-[#ccd6d1] bg-white px-3 text-sm font-bold outline-none focus:border-[#16725e] focus:ring-2 focus:ring-[#16725e]/20";

export function WorkoutHistory(){
 const [rows,setRows]=useState<WorkoutRow[]>(()=>initialWorkouts.map((row)=>({...row})) as WorkoutRow[]); const [showForm,setShowForm]=useState(false);
 const [providerId,setProviderId]=useState<MachineProviderId>("unknown"); const [modelId,setModelId]=useState(UNKNOWN_MODEL_ID); const [machineClassId,setMachineClassId]=useState<Exclude<MachineClassId,"all-comparable">>("unknown"); const [otherModel,setOtherModel]=useState(""); const [connectionMethod,setConnectionMethod]=useState("manual"); const [entryVerification,setEntryVerification]=useState<Exclude<VerificationId,"all-accepted">>("manual");
 const [sessionType,setSessionType]=useState("all"); const [brandFilter,setBrandFilter]=useState<MachineProviderId|"all">("all"); const [modelFilter,setModelFilter]=useState("all"); const [machineFilter,setMachineFilter]=useState<MachineClassId>("all-comparable"); const [verification,setVerification]=useState<VerificationId>("all-accepted");
 const formModels=modelsForProvider(providerId); const filterModels=brandFilter==="all"?MACHINE_MODELS:modelsForProvider(brandFilter);
 const filtered=useMemo(()=>rows.filter((row)=>(sessionType==="all"||row.sessionType===sessionType)&&(brandFilter==="all"||row.providerId===brandFilter)&&(modelFilter==="all"||row.modelId===modelFilter)&&(machineFilter==="all-comparable"||row.machineClassId===machineFilter)&&(verification==="all-accepted"||row.verificationId===verification)),[rows,sessionType,brandFilter,modelFilter,machineFilter,verification]);
 function chooseProvider(value:MachineProviderId){setProviderId(value);const provider=getMachineProvider(value)!;setModelId(value==="unknown"?UNKNOWN_MODEL_ID:OTHER_MODEL_ID);setMachineClassId(provider.supportedClassIds[0]??"unknown");setConnectionMethod(provider.connectionCapabilities[0]??"manual");}
 function chooseModel(value:string){setModelId(value);const model=getMachineModel(value);if(model){setProviderId(model.providerId);setMachineClassId(model.suggestedClassId);}}
 function addWorkout(formData:FormData){const title=String(formData.get("title")||"Manual row");setRows((current)=>[{id:Date.now(),title,providerId,modelId,otherModel:otherModel||undefined,machineClassId,connectionMethod,verificationId:entryVerification,sessionType:"training",distance:String(formData.get("distance")||"—"),time:String(formData.get("time")||"—"),pace:"—",date:"Just now"},...current]);setShowForm(false);}
 function reset(){setSessionType("all");setBrandFilter("all");setModelFilter("all");setMachineFilter("all-comparable");setVerification("all-accepted");}
 return <>
  <button type="button" onClick={()=>setShowForm((open)=>!open)} aria-expanded={showForm} aria-controls="workout-entry" className="mt-6 inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-[#ff6b35] px-5 text-sm font-black text-white"><Plus size={17}/>{showForm?"Close workout form":"Log a workout"}</button>
  {showForm&&<section id="workout-entry" className="mt-4 rounded-3xl border border-[#dfe5e1] bg-white p-4 sm:p-6" aria-labelledby="workout-entry-title"><h2 id="workout-entry-title" className="font-black">Workout machine and source</h2><p className="mt-2 text-xs leading-5 text-[#718078]">Unknown machines remain valid training records. Imported sessions populate provider and model when available.</p><form action={addWorkout} className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-xs font-bold text-[#475b54]">Workout title<input name="title" className={selectClass} placeholder="Steady row"/></label><label className="text-xs font-bold text-[#475b54]">Distance<input name="distance" className={selectClass} placeholder="5,000 m"/></label><label className="text-xs font-bold text-[#475b54]">Time<input name="time" className={selectClass} placeholder="22:30"/></label><label className="text-xs font-bold text-[#475b54]">Machine brand<select className={selectClass} value={providerId} onChange={(e)=>chooseProvider(e.target.value as MachineProviderId)}>{MACHINE_PROVIDERS.filter((item)=>item.active).map((item)=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Machine model<select className={selectClass} value={modelId} onChange={(e)=>chooseModel(e.target.value)}>{formModels.map((item)=><option key={item.id} value={item.id}>{item.model}</option>)}<option value={OTHER_MODEL_ID}>Other model</option><option value={UNKNOWN_MODEL_ID}>Unknown model</option></select></label>{modelId===OTHER_MODEL_ID&&<label className="text-xs font-bold text-[#475b54]">Other model name<input className={selectClass} value={otherModel} onChange={(e)=>setOtherModel(e.target.value)}/></label>}<label className="text-xs font-bold text-[#475b54]">Machine class<select className={selectClass} value={machineClassId} onChange={(e)=>setMachineClassId(e.target.value as typeof machineClassId)}>{MACHINE_CLASSES.filter((item)=>item.id!=="all-comparable").map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Connection / source<select className={selectClass} value={connectionMethod} onChange={(e)=>setConnectionMethod(e.target.value)}>{CONNECTION_METHODS.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Verification tier<select className={selectClass} value={entryVerification} onChange={(e)=>setEntryVerification(e.target.value as typeof entryVerification)}>{VERIFICATION_OPTIONS.filter((item)=>item.id!=="all-accepted").map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><div className="sm:col-span-2 lg:col-span-3"><button className="min-h-11 rounded-full bg-[#0d2b24] px-5 text-sm font-black text-white">Save prototype workout</button></div></form></section>}
  <section className="mt-6 rounded-3xl border border-[#dfe5e1] bg-white p-4" aria-labelledby="workout-filters"><div className="flex items-center justify-between gap-3"><h2 id="workout-filters" className="flex items-center gap-2 font-black"><Filter size={17}/>Workout filters</h2><button type="button" onClick={reset} className="inline-flex min-h-11 items-center gap-2 px-2 text-xs font-black text-[#16725e]"><RotateCcw size={14}/>Reset</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs font-bold text-[#475b54]">Workout role<select className={selectClass} value={sessionType} onChange={(e)=>setSessionType(e.target.value)}>{sessionTypes.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Machine brand<select className={selectClass} value={brandFilter} onChange={(e)=>{setBrandFilter(e.target.value as typeof brandFilter);setModelFilter("all");}}><option value="all">All brands</option>{MACHINE_PROVIDERS.filter((item)=>item.active).map((item)=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Machine model<select className={selectClass} value={modelFilter} onChange={(e)=>setModelFilter(e.target.value)}><option value="all">All models</option>{filterModels.map((item)=><option key={item.id} value={item.id}>{brandFilter==="all"?`${getMachineProvider(item.providerId)?.displayName} ${item.model}`:item.model}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Machine class<select className={selectClass} value={machineFilter} onChange={(e)=>setMachineFilter(e.target.value as MachineClassId)}>{MACHINE_CLASSES.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label className="text-xs font-bold text-[#475b54]">Verification<select className={selectClass} value={verification} onChange={(e)=>setVerification(e.target.value as VerificationId)}>{VERIFICATION_OPTIONS.map((item)=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label></div></section>
  <section className="mt-4 overflow-hidden rounded-3xl border border-[#dfe5e1] bg-white" aria-label="Workout history">{filtered.map((workout)=>{const provider=getMachineProvider(workout.providerId);const model=getMachineModel(workout.modelId);const body=<article className="grid border-b border-[#e7ebe8] p-5 last:border-0 sm:grid-cols-[1.7fr_1fr_1fr] sm:items-center sm:px-6"><div><h2 className="font-black text-[#263a34]">{workout.title}</h2><p className="mt-1 text-xs font-bold text-[#475b54]">{provider?.displayName??"Unknown"} {model?.model??workout.otherModel??"Unknown model"} · {labelFor(MACHINE_CLASSES,workout.machineClassId)}</p><p className="mt-1 text-xs text-[#718078]">{workout.date} · {CONNECTION_METHODS.find((item)=>item.id===workout.connectionMethod)?.label??workout.connectionMethod}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-full bg-[#eef3f0] px-2 py-1 text-[10px] font-bold">{sessionTypes.find((item)=>item.id===workout.sessionType)?.label}</span><span className="inline-flex items-center gap-1 rounded-full bg-[#eaf6f1] px-2 py-1 text-[10px] font-bold text-[#176a55]"><ShieldCheck size={10}/>{labelFor(VERIFICATION_OPTIONS,workout.verificationId)}</span></div></div><div className="mt-4 flex justify-between sm:mt-0 sm:block"><span className="text-xs text-[#8b9892] sm:hidden">Distance</span><strong>{workout.distance}</strong></div><div className="mt-2 flex justify-between sm:mt-0 sm:block"><span className="text-xs text-[#8b9892] sm:hidden">Time</span><strong>{workout.time}</strong></div></article>;return workout.detailId?<Link key={workout.id} href={`/workouts/${workout.detailId}`} className="block hover:bg-[#fbfcfb] focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-[#16725e]" aria-label={`View details for ${workout.title}`}>{body}</Link>:<div key={workout.id}>{body}</div>;})}{!filtered.length&&<div className="p-10 text-center text-sm font-bold text-[#718078]">No workouts match these filters.</div>}</section>
 </>;
}
