import { COUNTRY_RANKING_REGION, type RankingRegion } from "./regions";

export type GeographicScope = "World" | "Continent" | "Country" | "Club";
export interface RankingRecord { id: string; athleteName: string; initials: string; countryCode: string; country: string; clubId?: string; club?: string; season: string; distanceMeters: number; ageCategory: string; competitionCategory: string; weightCategory: string; machineClass: string; verificationTier: string; result: string; resultMilliseconds: number; current?: boolean; }
export interface RankingFilters { scope: GeographicScope; region: RankingRegion; countryCode: string; clubId: string; season: string; distanceMeters: number; ageCategory: string; competitionCategory: string; weightCategory: string; machineClass: string; verificationTier: string; }

export const RANKING_RECORDS: RankingRecord[] = [
  { id:"r1", athleteName:"Jonas Richter", initials:"JR", countryCode:"DE", country:"Germany", clubId:"00000000-0000-4000-8000-000000000108", club:"Berliner Ruder-Club", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:31.8", resultMilliseconds:391800 },
  { id:"r2", athleteName:"Samuel Okafor", initials:"SO", countryCode:"NG", country:"Nigeria", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:42.1", resultMilliseconds:402100 },
  { id:"r3", athleteName:"Yacine Benali", initials:"YB", countryCode:"DZ", country:"Algeria", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:58.4", resultMilliseconds:418400 },
  { id:"r4", athleteName:"Mohamed Djebbari", initials:"MD", countryCode:"DZ", country:"Algeria", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"7:12.4", resultMilliseconds:432400, current:true },
  { id:"r5", athleteName:"Amine Rahal", initials:"AR", countryCode:"DZ", country:"Algeria", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"7:18.9", resultMilliseconds:438900 },
  { id:"r6", athleteName:"Liam O'Connor", initials:"LO", countryCode:"IE", country:"Ireland", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:49.7", resultMilliseconds:409700 },
  { id:"r7", athleteName:"Noah Williams", initials:"NW", countryCode:"US", country:"United States", clubId:"00000000-0000-4000-8000-000000000104", club:"Community Rowing, Inc.", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:39.5", resultMilliseconds:399500 },
  { id:"r8", athleteName:"Lucas Pereira", initials:"LP", countryCode:"BR", country:"Brazil", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:55.0", resultMilliseconds:415000 },
  { id:"r9", athleteName:"Hiro Tanaka", initials:"HT", countryCode:"JP", country:"Japan", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:46.2", resultMilliseconds:406200 },
  { id:"r10", athleteName:"Oliver Smith", initials:"OS", countryCode:"AU", country:"Australia", clubId:"00000000-0000-4000-8000-000000000105", club:"Sydney Rowing Club", season:"2026", distanceMeters:2000, ageCategory:"30–39", competitionCategory:"Men", weightCategory:"Open", machineClass:"Standard air resistance", verificationTier:"Tier 2+", result:"6:37.4", resultMilliseconds:397400 },
];

export function filterRankings(records: RankingRecord[], filters: RankingFilters) {
  return records.filter((record) => record.season === filters.season && record.distanceMeters === filters.distanceMeters && record.ageCategory === filters.ageCategory && record.competitionCategory === filters.competitionCategory && record.weightCategory === filters.weightCategory && record.machineClass === filters.machineClass && record.verificationTier === filters.verificationTier && (filters.scope === "World" || (filters.scope === "Continent" && COUNTRY_RANKING_REGION[record.countryCode] === filters.region) || (filters.scope === "Country" && record.countryCode === filters.countryCode) || (filters.scope === "Club" && record.clubId === filters.clubId))).sort((a,b) => a.resultMilliseconds-b.resultMilliseconds);
}
