"use client";

import { useEffect, useId, useState } from "react";
import { Check, MapPin } from "lucide-react";
import type { CitySelection } from "@/lib/location-data/types";

export function CityCombobox({ countryCode, value, onChange, required = false }: { countryCode: string; value: CitySelection | null; onChange: (city: CitySelection | null) => void; required?: boolean }) {
  const id = useId(); const listId = `${id}-cities`; const [query, setQuery] = useState(value?.name ?? ""); const [options, setOptions] = useState<CitySelection[]>([]); const [open, setOpen] = useState(false); const [active, setActive] = useState(0); const [manual, setManual] = useState(value?.source === "manual");
  useEffect(() => {
    if (!countryCode || manual) return;
    const controller = new AbortController();
    const timer = window.setTimeout(async () => { const response = await fetch(`/api/locations/cities?country=${countryCode}&q=${encodeURIComponent(query)}`, { signal: controller.signal }); if (response.ok) { const data = await response.json() as { cities: CitySelection[] }; setOptions(data.cities); } }, 180);
    return () => { window.clearTimeout(timer); controller.abort(); };
  }, [countryCode, query, manual]);
  const allOptions = [...options, { name: "Other city / not listed", countryCode, source: "manual" as const }];
  function choose(city: CitySelection) { if (city.source === "manual") { setManual(true); setQuery(""); onChange({ name: "", countryCode, source: "manual" }); } else { setQuery(city.name); onChange(city); } setOpen(false); }
  if (manual) return <div><label htmlFor={id} className="text-xs font-bold text-[#475b54]">City or locality<input id={id} required={required} value={value?.name ?? ""} onChange={(event) => onChange({ name: event.target.value, countryCode, source: "manual" })} placeholder="Enter your city or locality" className="mt-1.5 min-h-11 w-full rounded-xl border border-[#ccd6d1] px-3 text-sm font-bold outline-none focus:border-[#16725e] focus:ring-2 focus:ring-[#16725e]/20" /></label><button type="button" onClick={() => { setManual(false); setQuery(""); onChange(null); }} className="mt-2 text-xs font-bold text-[#16725e] underline">Choose from city dataset</button></div>;
  return <div className="relative"><label htmlFor={id} className="text-xs font-bold text-[#475b54]">City <span className="font-normal">(optional)</span></label><div className="relative mt-1.5"><MapPin size={16} className="absolute left-3 top-3.5 text-[#718078]" /><input id={id} role="combobox" aria-expanded={open} aria-controls={listId} aria-activedescendant={open && allOptions[active] ? `${listId}-${active}` : undefined} disabled={!countryCode} value={query} placeholder={countryCode ? "Search cities" : "Choose a country first"} autoComplete="off" onFocus={() => setOpen(true)} onBlur={() => window.setTimeout(() => setOpen(false), 120)} onChange={(event) => { setQuery(event.target.value); onChange(null); setOpen(true); setActive(0); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((index) => Math.min(index + 1, allOptions.length - 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((index) => Math.max(index - 1, 0)); } if (event.key === "Enter" && open && allOptions[active]) { event.preventDefault(); choose(allOptions[active]); } if (event.key === "Escape") setOpen(false); }} className="min-h-11 w-full rounded-xl border border-[#ccd6d1] bg-white py-2 pl-9 pr-3 text-sm font-bold outline-none focus:border-[#16725e] focus:ring-2 focus:ring-[#16725e]/20 disabled:bg-[#eef3f0]" /></div>{open && <ul id={listId} role="listbox" className="absolute z-50 mt-1 max-h-56 w-full overflow-y-auto rounded-xl border border-[#ccd6d1] bg-white p-1 shadow-xl">{allOptions.map((city, index) => <li id={`${listId}-${index}`} key={`${city.name}-${city.region ?? ""}`} role="option" aria-selected={value?.name === city.name && value?.region === city.region} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(city)} className={`flex cursor-pointer gap-2 rounded-lg px-3 py-2 text-sm ${active === index ? "bg-[#eef3f0]" : "hover:bg-[#f5f7f4]"}`}><Check size={15} className={value?.name === city.name ? "text-[#16725e]" : "text-transparent"} /><span><strong>{city.name}</strong>{city.region && <span className="ml-2 text-xs text-[#718078]">{city.region}</span>}</span></li>)}</ul>}<p className="mt-2 text-[11px] leading-5 text-[#718078]">City coverage comes from a maintained global dataset and is broad, not universally complete.</p></div>;
}
